### ISSUE TITLE
TypeError: 'multiple' is not valid with 'is_flag', use 'count'.

### ISSUE THREAD

**Issue by twiecki** [lektor/lektor#1031]
```
Run lektor build --output-path site/
[8](https://github.com/pymc-labs/pymc-labs-website-source/runs/6226189455?check_suite_focus=true#step:8:8)
Traceback (most recent call last):
[9](https://github.com/pymc-labs/pymc-labs-website-source/runs/6226189455?check_suite_focus=true#step:8:9)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/bin/lektor", line 5, in <module>
[10](https://github.com/pymc-labs/pymc-labs-website-source/runs/6226189455?check_suite_focus=true#step:8:10)
    from lektor.cli import main
[11](https://github.com/pymc-labs/pymc-labs-website-source/runs/6226189455?check_suite_focus=true#step:8:11)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/lektor/cli.py", line 392, in <module>
[12](https://github.com/pymc-labs/pymc-labs-website-source/runs/6226189455?check_suite_focus=true#step:8:12)
    def project_info_cmd(ctx, as_json, ops):
[13](https://github.com/pymc-labs/pymc-labs-website-source/runs/6226189455?check_suite_focus=true#step:8:13)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/click/decorators.py", line 308, in decorator
[14](https://github.com/pymc-labs/pymc-labs-website-source/runs/6226189455?check_suite_focus=true#step:8:14)
    _param_memo(f, OptionClass(param_decls, **option_attrs))
[15](https://github.com/pymc-labs/pymc-labs-website-source/runs/6226189455?check_suite_focus=true#step:8:15)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/click/core.py", line 2584, in __init__
[16](https://github.com/pymc-labs/pymc-labs-website-source/runs/6226189455?check_suite_focus=true#step:8:16)
    raise TypeError("'multiple' is not valid with 'is_flag', use 'count'.")
[17](https://github.com/pymc-labs/pymc-labs-website-source/runs/6226189455?check_suite_focus=true#step:8:17)
TypeError: 'multiple' is not valid with 'is_flag', use 'count'.
```

Versions: `Babel-2.10.1 EXIFRead-2.3.2 MarkupSafe-2.1.1 Werkzeug-2.1.2 certifi-2021.10.8 charset-normalizer-2.0.12 click-8.1.3 filetype-1.0.13 flask-2.1.2 idna-3.3 importlib-metadata-4.11.3 inifile-0.4.1 itsdangerous-2.1.2 jinja2-3.1.2 lektor-3.3.3 mistune-0.8.4 python-slugify-6.1.2 pytz-2022.1 requests-2.27.1 text-unidecode-1.3 urllib3-1.26.9 watchdog-2.1.7 zipp-3.8.0`

**Comment by sfermigier** [comment]
This happened since the `click` upgrade from 8.1.2 to 8.1.3.

Pinning down `click` to version 8.1.2 solves the issue.

**Comment by twiecki** [comment]
That worked, thanks!

**Comment by animeshkrishnabulusu** [comment]
I have fixed this in deployment pipeline by including 

```
    - pip3 install lektor
    - pip3 install click==8.1.2
```

Locally I am facing the issue after a Lektor reinstall. I did install click 8.1.2 locally, but Lektor packages still has the 8.1.3 version.
How do I make local Lektor use the old package?

**Comment by animeshkrishnabulusu** [comment]
I uninstalled Lektor and reinstalled it with pipx.
Then installed click 8.1.2 directly into the site-packages directory where lektor lives.

```
pip install --target=C:\Users\anmsh\.local\pipx\venvs\lektor\Lib\site-packages click==8.1.2 --upgrade
```

Then I could run Lektor successfully.
