### ISSUE TITLE
Development setup errors when used with --extra-flag

### ISSUE THREAD

**Issue by bockstaller** [lektor/lektor#1041]
I have installed the [development version ](https://www.getlektor.com/docs/installation/) of lektor and created the quickstart blog. Running `lektor server --extra-flag SOME-FLAG` results in the following stacktrace:

```
Started prune
Finished prune in 0.01 sec
Traceback (most recent call last):
  File "C:\Users\Lukas\code\repro\venv\lib\site-packages\flask\app.py", line 2095, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Lukas\code\repro\venv\lib\site-packages\flask\app.py", line 2080, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Lukas\code\repro\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Lukas\code\repro\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Lukas\code\repro\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Lukas\code\repro\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\users\lukas\code\repro\lektor\lektor\admin\modules\serve.py", line 230, in serve_artifact_or_file
    return serve_artifact(path)
  File "c:\users\lukas\code\repro\lektor\lektor\admin\modules\serve.py", line 202, in serve_artifact
    return ArtifactServer(lektor_context).serve_artifact(path)
  File "c:\users\lukas\code\repro\lektor\lektor\admin\modules\serve.py", line 186, in serve_artifact
    artifact, failure = self.build_primary_artifact(source)
  File "c:\users\lukas\code\repro\lektor\lektor\admin\modules\serve.py", line 139, in build_primary_artifact
    prog, _ = lektor_ctx.builder.build(source)
  File "C:\Users\Lukas\code\repro\venv\lib\site-packages\werkzeug\utils.py", line 107, in __get__
    value = self.fget(obj)  # type: ignore
  File "c:\users\lukas\code\repro\lektor\lektor\admin\context.py", line 62, in builder
    return Builder(self.pad, self.output_path, self.extra_flags)
  File "c:\users\lukas\code\repro\lektor\lektor\builder.py", line 1056, in __init__
    os.makedirs(self.meta_path)
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python310\lib\os.py", line 210, in makedirs
    head, tail = path.split(name)
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 185, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not dict
``` 

My investigation suggests that the culprit here is this call with positional instead of keyword arguments:
https://github.com/lektor/lektor/blob/8ae1939bd4182f36a5749e4355128c3810036ed0/lektor/admin/context.py#L62
`Builder` is expecting a `buildstate_path` and gets handed an `extra_flags` dict.
https://github.com/lektor/lektor/blob/8ae1939bd4182f36a5749e4355128c3810036ed0/lektor/builder.py#L1042-L1043

But I am not sure if this is the root cause as I can't reproduce this error with a regular install.

**Comment by bockstaller** [comment]
The regression was introduced in this commit: ae3d682924286f0a8bf6a29c0ef524e19daaa7a3 and isn't released yet. Which explains why I wasn't able to reproduce
