### ISSUE TITLE
Using lektor installed with pip fails.

### ISSUE THREAD

**Issue by GrahamDumpleton** [lektor/lektor#113]
I know your web site says:

**When we say this installation type is discouraged we mean it. The reason is that it encourages uses of Lektor which are entirely unsupported by us. Lektor actively manages virtualenvs for plugin installations in very specific ways and this might or might not work in your setup. We support pip installations for deployment environments and local development only.**

but I am trying to use Lektor in what is a deployment environment of sorts, which you sort of do say you will support.

The problem is that I use:

```
pip install Lektor
```

and then later:

```
lektor build --output-path /data
```

in the directory of the project, then it eventually fails with the output:

```
Updating packages in /home/whiskey/.cache/lektor/packages/4a18bd5447c737ad6b5ff8baf4acafe6 for project
Collecting lektor-webpack-support==0.1
  Downloading lektor_webpack_support-0.1-py2-none-any.whl
Installing collected packages: lektor-webpack-support
Successfully installed lektor-webpack-support
Collecting lektor-markdown-highlighter==0.1
  Downloading lektor_markdown_highlighter-0.1-py2-none-any.whl
Collecting Pygments (from lektor-markdown-highlighter==0.1)
  Downloading Pygments-2.0.2-py2-none-any.whl (672kB)
    100% |████████████████████████████████| 675kB 568kB/s
Installing collected packages: Pygments, lektor-markdown-highlighter
Successfully installed Pygments lektor-markdown-highlighter
Collecting lektor-markdown-admonition==0.1
  Downloading lektor_markdown_admonition-0.1-py2-none-any.whl
Installing collected packages: lektor-markdown-admonition
Successfully installed lektor-markdown-admonition
Collecting lektor-markdown-header-anchors==0.1
  Downloading lektor_markdown_header_anchors-0.1-py2-none-any.whl
Installing collected packages: lektor-markdown-header-anchors
Successfully installed lektor-markdown-header-anchors
Collecting lektor-disqus-comments==0.1
  Downloading lektor_disqus_comments-0.1-py2-none-any.whl
Installing collected packages: lektor-disqus-comments
Successfully installed lektor-disqus-comments
Collecting lektor-atom==0.1
  Downloading lektor-atom-0.1.tar.gz
Collecting MarkupSafe (from lektor-atom==0.1)
Collecting Lektor (from lektor-atom==0.1)
  Using cached Lektor-1.1-py2-none-any.whl
Collecting setuptools (from Lektor->lektor-atom==0.1)
  Downloading setuptools-19.4-py2.py3-none-any.whl (471kB)
    100% |████████████████████████████████| 475kB 203kB/s
Collecting Jinja2>=2.4 (from Lektor->lektor-atom==0.1)
  Using cached Jinja2-2.8-py2.py3-none-any.whl
Collecting EXIFRead (from Lektor->lektor-atom==0.1)
  Using cached ExifRead-2.1.2-py2-none-any.whl
Collecting pip (from Lektor->lektor-atom==0.1)
  Downloading pip-7.1.2-py2.py3-none-any.whl (1.1MB)
    100% |████████████████████████████████| 1.1MB 131kB/s
Collecting click>=6.0 (from Lektor->lektor-atom==0.1)
  Using cached click-6.2-py2.py3-none-any.whl
Collecting inifile (from Lektor->lektor-atom==0.1)
  Using cached inifile-0.3-py2-none-any.whl
Collecting requests[security] (from Lektor->lektor-atom==0.1)
  Using cached requests-2.9.1-py2.py3-none-any.whl
Collecting watchdog (from Lektor->lektor-atom==0.1)
Collecting mistune (from Lektor->lektor-atom==0.1)
  Using cached mistune-0.7.1-py2.py3-none-any.whl
Collecting Babel (from Lektor->lektor-atom==0.1)
  Using cached Babel-2.2.0-py2.py3-none-any.whl
Collecting Flask (from Lektor->lektor-atom==0.1)
Collecting ndg-httpsclient (from requests[security]->Lektor->lektor-atom==0.1)
Collecting pyOpenSSL>=0.13 (from requests[security]->Lektor->lektor-atom==0.1)
  Using cached pyOpenSSL-0.15.1-py2.py3-none-any.whl
Collecting pyasn1 (from requests[security]->Lektor->lektor-atom==0.1)
  Using cached pyasn1-0.1.9-py2.py3-none-any.whl
Collecting argh>=0.24.1 (from watchdog->Lektor->lektor-atom==0.1)
Collecting PyYAML>=3.10 (from watchdog->Lektor->lektor-atom==0.1)
Collecting pathtools>=0.1.1 (from watchdog->Lektor->lektor-atom==0.1)
Collecting pytz>=0a (from Babel->Lektor->lektor-atom==0.1)
  Using cached pytz-2015.7-py2.py3-none-any.whl
Collecting itsdangerous>=0.21 (from Flask->Lektor->lektor-atom==0.1)
Collecting Werkzeug>=0.7 (from Flask->Lektor->lektor-atom==0.1)
  Using cached Werkzeug-0.11.3-py2.py3-none-any.whl
Collecting cryptography>=0.7 (from pyOpenSSL>=0.13->requests[security]->Lektor->lektor-atom==0.1)
Collecting six>=1.5.2 (from pyOpenSSL>=0.13->requests[security]->Lektor->lektor-atom==0.1)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting enum34 (from cryptography>=0.7->pyOpenSSL>=0.13->requests[security]->Lektor->lektor-atom==0.1)
Collecting ipaddress (from cryptography>=0.7->pyOpenSSL>=0.13->requests[security]->Lektor->lektor-atom==0.1)
  Using cached ipaddress-1.0.16-py27-none-any.whl
Collecting idna>=2.0 (from cryptography>=0.7->pyOpenSSL>=0.13->requests[security]->Lektor->lektor-atom==0.1)
  Using cached idna-2.0-py2.py3-none-any.whl
Collecting cffi>=1.4.1 (from cryptography>=0.7->pyOpenSSL>=0.13->requests[security]->Lektor->lektor-atom==0.1)
Collecting pycparser (from cffi>=1.4.1->cryptography>=0.7->pyOpenSSL>=0.13->requests[security]->Lektor->lektor-atom==0.1)
Building wheels for collected packages: lektor-atom
  Running setup.py bdist_wheel for lektor-atom
  Stored in directory: /home/whiskey/.cache/pip/wheels/a9/be/8b/f73eeb11e19c18c8c8c6b8f0d390ca40464a120ec915a35429
Successfully built lektor-atom
Installing collected packages: MarkupSafe, setuptools, Jinja2, EXIFRead, pip, click, inifile, enum34, ipaddress, idna, pyasn1, pycparser, cffi, six, cryptography, pyOpenSSL, ndg-httpsclient, requests, argh, PyYAML, pathtools, watchdog, mistune, pytz, Babel, itsdangerous, Werkzeug, Flask, Lektor, lektor-atom
Successfully installed Babel-2.2.0 EXIFRead-2.1.2 Flask-0.10.1 Jinja2-2.8 Lektor-1.1 MarkupSafe-0.23 PyYAML-3.11 Werkzeug-0.11.3 argh-0.26.1 cffi-1.5.0 click-6.2 cryptography-1.2.1 enum34-1.1.2 idna-2.0 inifile-0.3 ipaddress-1.0.16 itsdangerous-0.24 lektor-atom mistune-0.7.1 ndg-httpsclient-0.4.0 pathtools-0.1.2 pip-7.1.2 pyOpenSSL-0.15.1 pyasn1-0.1.9 pycparser-2.14 pytz-2015.7 requests-2.9.1 setuptools-19.2 six-1.10.0 watchdog-0.8.3
/home/whiskey/.cache/lektor/packages/4a18bd5447c737ad6b5ff8baf4acafe6/pip/commands/install.py:199: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
Obtaining file:///app/packages/markdown-link-classes
Installing collected packages: lektor-markdown-link-classes
  Running setup.py develop for lektor-markdown-link-classes
Successfully installed lektor-markdown-link-classes
/home/whiskey/.cache/lektor/packages/4a18bd5447c737ad6b5ff8baf4acafe6/pip/commands/install.py:199: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
Obtaining file:///app/packages/blog-archive
Installing collected packages: lektor-blog-archive
  Running setup.py develop for lektor-blog-archive
Successfully installed lektor-blog-archive
Traceback (most recent call last):
  File "/usr/local/python/bin/lektor", line 11, in <module>
    sys.exit(main())
  File "/usr/local/python/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/python/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/python/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/python/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/python/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/python/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/python/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/python/lib/python2.7/site-packages/lektor/cli.py", line 159, in build_cmd
    ctx.load_plugins()
  File "/usr/local/python/lib/python2.7/site-packages/lektor/cli.py", line 84, in load_plugins
    initialize_plugins(self.get_env())
  File "/usr/local/python/lib/python2.7/site-packages/lektor/pluginsystem.py", line 121, in initialize_plugins
    plugins = load_plugins()
  File "/usr/local/python/lib/python2.7/site-packages/lektor/pluginsystem.py", line 115, in load_plugins
    rv[ep.name] = ep.load()
  File "/usr/local/python/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2380, in load
    return self.resolve()
  File "/usr/local/python/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2386, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/whiskey/.cache/lektor/packages/4a18bd5447c737ad6b5ff8baf4acafe6/lektor_atom.py", line 14, in <module>
    from lektor.utils import build_url
ImportError: cannot import name build_url
```

The problem is that the build phase is triggering some update which is pulling down code which is dependent on unreleased code in Lektor. IOW, `lektor.utils.build_url()` doesn't exist in Lektor 1.1.

```
$ pip freeze
argh==0.26.1
Babel==2.2.0
cffi==1.5.0
click==6.2
cryptography==1.2.1
enum34==1.1.2
ExifRead==2.1.2
Flask==0.10.1
idna==2.0
inifile==0.3
ipaddress==1.0.16
itsdangerous==0.24
Jinja2==2.8
Lektor==1.1
MarkupSafe==0.23
mistune==0.7.1
mod-wsgi==4.4.21
ndg-httpsclient==0.4.0
pathtools==0.1.2
pyasn1==0.1.9
pycparser==2.14
pyOpenSSL==0.15.1
pytz==2015.7
PyYAML==3.11
requests==2.9.1
six==1.10.0
watchdog==0.8.3
Werkzeug==0.11.3
wheel==0.26.0
```

I have tried to use:

```
curl -sf https://www.getlektor.com/install.sh | sh
```

but that also fails in my case as I am running it the `Dockerfile` for a Docker build and this script will blow up because it is trying to open `/dev/tty` which will not exist in a Docker container when being built.

```
Step 2 : RUN curl -sf https://www.getlektor.com/install.sh | sh
 ---> Running in d135cae830fc
Traceback (most recent call last):
  File "<stdin>", line 11, in <module>
IOError: [Errno 6] No such device or address: '/dev/tty'
The command '/bin/sh -c curl -sf https://www.getlektor.com/install.sh | sh' returned a non-zero code: 1
```

Suggestions on how to install Lektor as part of a Docker build so it will work?

**Comment by GrahamDumpleton** [comment]
Okay. At a guess I might know what the issue is.

I am actually trying to use `lektor-site` as the Git repository to use for my automated build system for the deployment of a Lektor site. That may be a bad example as set up for latest.

Will do test with site not created by newer Lektor.

**Comment by GrahamDumpleton** [comment]
Yep. That was the problem.

Was a useful lesson to learn though. Any automated build system for deploying a Lektor site from a Git repository will need to provide multiple builder versions for different Lektor versions if going to have this situation where project created with newer Lektor will not work with older version. The user will need to select the correct version of the builder to use for the version of their project.

**Comment by odeckmyn** [comment]
same issue here just trying to build lektor-website on my laptop (to get the documentation while offline) 

How did you manage to bypass this error and build the website finally ?

Thanx

**Comment by GrahamDumpleton** [comment]
I just didn't use Lektor's own web site in the end.

If you want to build up their web site as an example I would imagine you have to use latest development version of Lektor. So see how to install it in:
- https://www.getlektor.com/docs/installation/

Section 'Development Version'.

For purposes of what I was doing I just created an empty Lektor site using the latest version off PyPi. You can see what I was doing in blog post at:
- http://blog.dscpl.com.au/2016/01/automating-deployment-of-lektor-blog.html

**Comment by odeckmyn** [comment]
:+1:
