### ISSUE TITLE
Enable dev mode results in error

### ISSUE THREAD

**Issue by bngsudheer** [lektor/lektor#1141]
```
export LEKTOR_DEV=1
```

```
lektor server
 * Project path: /home/sudheer/workspace/sudheer-projects/techchorus/techchorus.lektorproject
 * Output path: /home/sudheer/.cache/lektor/builds/9fe82daa28bc2e84957055a5751e265f
Traceback (most recent call last):
  File "/home/sudheer/.local/bin/lektor", line 8, in <module>
    sys.exit(main())
  File "/home/sudheer/.local/pipx/venvs/lektor/lib/python3.10/site-packages/lektor/cli.py", line 621, in main
    cli.main(args=args, prog_name=name)
  File "/home/sudheer/.local/pipx/venvs/lektor/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/sudheer/.local/pipx/venvs/lektor/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sudheer/.local/pipx/venvs/lektor/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sudheer/.local/pipx/venvs/lektor/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/sudheer/.local/pipx/venvs/lektor/lib/python3.10/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/sudheer/.local/pipx/venvs/lektor/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/sudheer/.local/pipx/venvs/lektor/lib/python3.10/site-packages/lektor/cli.py", line 344, in server_cmd
    run_server(
  File "/home/sudheer/.local/pipx/venvs/lektor/lib/python3.10/site-packages/lektor/devserver.py", line 140, in run_server
    dt.start()
  File "/home/sudheer/.local/pipx/venvs/lektor/lib/python3.10/site-packages/lektor/devserver.py", line 70, in start
    portable_popen(["npm", "install"], cwd=frontend).wait()
  File "/home/sudheer/.local/pipx/venvs/lektor/lib/python3.10/site-packages/lektor/utils.py", line 500, in portable_popen
    return subprocess.Popen(cmd, *args, **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/sudheer/.local/pipx/venvs/lektor/lib/python3.10/site-packages/lektor/../frontend'
```
Lektor, version 3.3.6

Expected Lektor to serve pages. But results in error.

**Comment by dairiki** [comment]
This was a known bug in 3.3.6.  It is fixed in 3.3.7. (See #1072)

Closing. Feel free to reopen if 3.3.7 (or 3.3.9) doesn't fix your issues.
