### ISSUE TITLE
Lektor does not like spaces in attachment filenames

### ISSUE THREAD

**Issue by jonasvp** [lektor/lektor#123]
Pictures from my phone camera are named by date/time, such as: "2015-11-13 09:33:45.jpg"

When using them in lektor, it gets confused when I click on the attachment in the admin. So I can't add metadata. Renaming them to remove the space solves the issue.

Traceback:

```
Traceback (most recent call last):
  File "/home/jonas/software/virtualenvs/lektor/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/jonas/software/virtualenvs/lektor/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/jonas/software/virtualenvs/lektor/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jonas/software/virtualenvs/lektor/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jonas/software/virtualenvs/lektor/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jonas/software/virtualenvs/lektor/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jonas/software/virtualenvs/lektor/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jonas/software/virtualenvs/lektor/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jonas/software/lektor/lektor/admin/modules/api.py", line 149, in get_raw_record
    ts = g.admin_context.tree.edit(request.args['path'], alt=alt)
  File "/home/jonas/software/lektor/lektor/db.py", line 1653, in edit
    datamodel=datamodel)
  File "/home/jonas/software/lektor/lektor/editor.py", line 45, in make_editor_session
    raise BadEdit('Invalid ID')
BadEdit: Invalid ID
```

**Comment by mitsuhiko** [comment]
Yeah, this needs some consideration currently. Attachments currently have to be valid IDs.
