### ISSUE TITLE
[ubuntu] installation fail 

### ISSUE THREAD

**Issue by kmonsoor** [lektor/lektor#125]
Install failed using the `curl` method.

Tried both on main system and in `conda` virtual-environment. same issue.

**OS**: Ubuntu 14.04 64-bit
## error log

```
vagrant@flangular:~$ curl -sf https://www.getlektor.com/install.sh | sh

Welcome to Lektor

This script will install Lektor on your computer.

   Lektor seems to be installed already.
   Continuing will wipe /home/vagrant/.local/lib/lektor and remove /home/vagrant/anaconda/bin/lektor

Continue? [Yn]

Installing at:
  bin: /home/vagrant/anaconda/bin
  app: /home/vagrant/.local/lib/lektor

Continue? [Yn]
New python executable in /home/vagrant/.local/lib/lektor/bin/python2
Also creating executable in /home/vagrant/.local/lib/lektor/bin/python
Installing setuptools, pip, wheel...
  Complete output from command /home/vagrant/.local/lib/lektor/bin/python2 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel:
  Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/tmpYMNAjY/virtualenv_support/pip-8.0.0-py2.py3-none-any.whl/pip/__init__.py", line 15, in <module>
  File "/tmp/tmpYMNAjY/virtualenv_support/pip-8.0.0-py2.py3-none-any.whl/pip/vcs/mercurial.py", line 9, in <module>
  File "/tmp/tmpYMNAjY/virtualenv_support/pip-8.0.0-py2.py3-none-any.whl/pip/download.py", line 38, in <module>
  File "/tmp/tmpYMNAjY/virtualenv_support/pip-8.0.0-py2.py3-none-any.whl/pip/_vendor/requests/__init__.py", line 58, in <module>
  File "/tmp/tmpYMNAjY/virtualenv_support/pip-8.0.0-py2.py3-none-any.whl/pip/_vendor/requests/utils.py", line 26, in <module>
  File "/tmp/tmpYMNAjY/virtualenv_support/pip-8.0.0-py2.py3-none-any.whl/pip/_vendor/requests/compat.py", line 7, in <module>
  File "/tmp/tmpYMNAjY/virtualenv_support/pip-8.0.0-py2.py3-none-any.whl/pip/_vendor/requests/packages/__init__.py", line 29, in <module>
ImportError: No module named urllib3
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "./virtualenv.py", line 2277, in <module>
    main()
  File "./virtualenv.py", line 702, in main
    symlink=options.symlink)
  File "./virtualenv.py", line 903, in create_environment
    download=download,
  File "./virtualenv.py", line 860, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env)
  File "./virtualenv.py", line 780, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/vagrant/.local/lib/lektor/bin/python2 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel failed with error code 1
Traceback (most recent call last):
  File "<stdin>", line 126, in <module>
  File "<stdin>", line 121, in main
  File "<stdin>", line 85, in install
  File "/home/vagrant/anaconda/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/home/vagrant/anaconda/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

vagrant@flangular:~$
vagrant@flangular:~$ pip install requests lxml cssselect
Requirement already satisfied (use --upgrade to upgrade): requests in ./anaconda/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): lxml in ./anaconda/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): cssselect in ./anaconda/lib/python2.7/site-packages
```

**Comment by mitsuhiko** [comment]
It would appear your pip installation is broken. Not sure how that happens.

**Comment by mitsuhiko** [comment]
I think you should report this issue against ubuntu or pip. This does not appear to be related to Lektor.
