### ISSUE TITLE
Ctrl + z server make Exception happened

### ISSUE THREAD

**Issue by defbobo** [lektor/lektor#13]
## lektor quick start finish

``` bash
That's all. Create project? [Y/n] 
```
## start fresh server

``` bash
root$ website  ls
0707  my_blog  my-website  themes
root$ website  cd 0707 
root$ 0707  ls
0707.lektorproject  assets  content  models  templates
root$ 0707  lektor server --host 0.0.0.0
 * Project path: /root/website/0707/0707.lektorproject
 * Output path: /root/.cache/lektor/builds/189bea412adc30a29326c49cc9d4d67e
Started source info update
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
Finished source info update in 0.08 sec
Started build
Finished build in 0.01 sec
Started prune
Finished prune in 0.00 sec
^Z
[1]  + 15360 suspended  lektor server --host 0.0.0.0
```
## after ctrl + z no response here

``` bash
root$ 0707  curl http://0.0.0.0:5000/
^C
```
## bring back the job, exception report

``` bash
root$ 0707  fg
[1]  + 15360 continued  lektor server --host 0.0.0.0
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 35493)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
```

**Comment by mitsuhiko** [comment]
Yeah, that's just something the socket server does. It's not a bug in the sense of it, it just logs that the client disconnected.
