### ISSUE TITLE
lektor command error with pkg_resources

### ISSUE THREAD

**Issue by item4** [lektor/lektor#188]
## Version of Lektor

master branch
## Version of Python

2.7.10 or lower
## Error

``` console
(lektor)[item4@item4-mbp item4.github.io]$ lektor build -f webpack
Traceback (most recent call last):
  File "/Users/item4/.virtualenvs/lektor/bin/lektor", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/Users/item4/.virtualenvs/lektor/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2905, in <module>
    @_call_aside
  File "/Users/item4/.virtualenvs/lektor/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2891, in _call_aside
    f(*args, **kwargs)
  File "/Users/item4/.virtualenvs/lektor/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2918, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/item4/.virtualenvs/lektor/lib/python2.7/site-packages/pkg_resources/__init__.py", line 642, in _build_master
    ws.require(__requires__)
  File "/Users/item4/.virtualenvs/lektor/lib/python2.7/site-packages/pkg_resources/__init__.py", line 947, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/item4/.virtualenvs/lektor/lib/python2.7/site-packages/pkg_resources/__init__.py", line 814, in resolve
    if req.marker and not req.marker.evaluate():
  File "/Users/item4/.virtualenvs/lektor/lib/python2.7/site-packages/pkg_resources/_vendor/packaging/markers.py", line 278, in evaluate
    return _evaluate_markers(self._markers, current_environment)
  File "/Users/item4/.virtualenvs/lektor/lib/python2.7/site-packages/pkg_resources/_vendor/packaging/markers.py", line 203, in _evaluate_markers
    lhs_value = _get_env(environment, lhs.value)
  File "/Users/item4/.virtualenvs/lektor/lib/python2.7/site-packages/pkg_resources/_vendor/packaging/markers.py", line 185, in _get_env
    "{0!r} does not exist in evaluation environment.".format(name)
pkg_resources._vendor.packaging.markers.UndefinedEnvironmentName: 'extra' does not exist in evaluation environment.
```
## How we can see it

``` pycon
(lektor)[item4@item4-mbp lektor]$ python
Python 2.7.10 (default, Sep 24 2015, 15:28:51)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> __requires__ = 'Lektor'
>>> import sys
>>> from pkg_resources import load_entry_point
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/item4/.virtualenvs/lektor/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2905, in <module>
    @_call_aside
  File "/Users/item4/.virtualenvs/lektor/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2891, in _call_aside
    f(*args, **kwargs)
  File "/Users/item4/.virtualenvs/lektor/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2918, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/item4/.virtualenvs/lektor/lib/python2.7/site-packages/pkg_resources/__init__.py", line 642, in _build_master
    ws.require(__requires__)
  File "/Users/item4/.virtualenvs/lektor/lib/python2.7/site-packages/pkg_resources/__init__.py", line 947, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/item4/.virtualenvs/lektor/lib/python2.7/site-packages/pkg_resources/__init__.py", line 814, in resolve
    if req.marker and not req.marker.evaluate():
  File "/Users/item4/.virtualenvs/lektor/lib/python2.7/site-packages/pkg_resources/_vendor/packaging/markers.py", line 278, in evaluate
    return _evaluate_markers(self._markers, current_environment)
  File "/Users/item4/.virtualenvs/lektor/lib/python2.7/site-packages/pkg_resources/_vendor/packaging/markers.py", line 203, in _evaluate_markers
    lhs_value = _get_env(environment, lhs.value)
  File "/Users/item4/.virtualenvs/lektor/lib/python2.7/site-packages/pkg_resources/_vendor/packaging/markers.py", line 185, in _get_env
    "{0!r} does not exist in evaluation environment.".format(name)
pkg_resources._vendor.packaging.markers.UndefinedEnvironmentName: 'extra' does not exist in evaluation environment.
>>>
```

**Comment by item4** [comment]
I used newest setuptools and it occur this error.

related issue: https://github.com/pypa/setuptools/issues/523

**Comment by item4** [comment]
Solution: Install `setuptools >= 20.6.7`.
