### ISSUE TITLE
Error while deploying a lektor project to hithub on windows dual python install

### ISSUE THREAD

**Issue by andoresuperesu** [lektor/lektor#191]
While trying to deploy to a github page i get the error below:

**Project file**

```
[project]
name = andresperezcera

[servers.production]
target = ghpages://andresperezcera/andresperezcera.github.io?cname=andresperezcera.xyz
```

**Error**

```
λ lektor deploy
Deploying to production
  Build cache: C:\Users\aperez\AppData\Roaming\Lektor\Cache\builds\75d505d25f90dec1e1ee1c5a3f9da1a3
  Target: ghpages://andresperezcera/andresperezcera.github.io?cname=andresperezcera.xyz
Traceback (most recent call last):
  File "C:\Python27\Lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\aperez\AppData\Local\lektor-cli\lib\Scripts\lektor.exe\__main__.py", line 9, in <module>
  File "c:\users\aperez\appdata\local\lektor-cli\lib\lib\site-packages\click\core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\aperez\appdata\local\lektor-cli\lib\lib\site-packages\click\core.py", line 696, in main
    rv = self.invoke(ctx)
  File "c:\users\aperez\appdata\local\lektor-cli\lib\lib\site-packages\click\core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\aperez\appdata\local\lektor-cli\lib\lib\site-packages\click\core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\aperez\appdata\local\lektor-cli\lib\lib\site-packages\click\core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "c:\users\aperez\appdata\local\lektor-cli\lib\lib\site-packages\click\decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "c:\users\aperez\appdata\local\lektor-cli\lib\lib\site-packages\click\core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "c:\users\aperez\appdata\local\lektor-cli\lib\lib\site-packages\lektor\cli.py", line 282, in deploy_cmd
    for line in event_iter:
  File "c:\users\aperez\appdata\local\lektor-cli\lib\lib\site-packages\lektor\publisher.py", line 583, in publish
    for line in git(['init']):
  File "c:\users\aperez\appdata\local\lektor-cli\lib\lib\site-packages\lektor\publisher.py", line 152, in safe_iter
    for line in self:
  File "c:\users\aperez\appdata\local\lektor-cli\lib\lib\site-packages\lektor\publisher.py", line 141, in __iter__
    for l in select.select(streams, [], streams):
select.error: (10038, 'Se intent\xf3 realizar una operaci\xf3n en un elemento que no es un socket')
There must be something missing in my project file. Perhaps the connection string doesn't work in windows or perhaps something else.
```

**Comment by mitsuhiko** [comment]
I have no idea how to fix that :(

**Comment by mitsuhiko** [comment]
I added a crude hack involving threads. I think this fixes it.
