### ISSUE TITLE
Python 3.5 doesn't work quickstart

### ISSUE THREAD

**Issue by nesffer** [lektor/lektor#204]
Python 3.5 doesn't work `lektor quickstart`

OS: Ubuntu 16.04

Lektor installed by master branch clone.

```
$ lektor quickstart
Lektor Quickstart
=================

This wizard will generate a new basic project with some sensible defaults for
getting started quickly.  We just need to go through a few questions so that
the project is set up correctly for you.

Step 1:
| A project needs a name.  The name is primarily used for the admin UI and
| some other places to refer to your project to not get confused if multiple
| projects exist.  You can change this at any later point.
> Project Name: nesffer.github.io
Traceback (most recent call last):
  File "/home/nesffer/dev/nesffer.github.io/bin/lektor", line 9, in <module>
    load_entry_point('Lektor', 'console_scripts', 'lektor')()
  File "/home/nesffer/dev/nesffer.github.io/lib/python3.5/site-packages/click-6.6-py3.5.egg/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/nesffer/dev/nesffer.github.io/lib/python3.5/site-packages/click-6.6-py3.5.egg/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/nesffer/dev/nesffer.github.io/lib/python3.5/site-packages/click-6.6-py3.5.egg/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/nesffer/dev/nesffer.github.io/lib/python3.5/site-packages/click-6.6-py3.5.egg/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/nesffer/dev/nesffer.github.io/lib/python3.5/site-packages/click-6.6-py3.5.egg/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/nesffer/dev/nesffer.github.io/lib/python3.5/site-packages/click-6.6-py3.5.egg/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/nesffer/dev/nesffer.github.io/lib/python3.5/site-packages/click-6.6-py3.5.egg/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/nesffer/dev/nesffer.github.io/lektor/lektor/cli.py", line 556, in quickstart_cmd
    project_quickstart(options)
  File "/home/nesffer/dev/nesffer.github.io/lektor/lektor/quickstart.py", line 171, in project_quickstart
    author_name = g.prompt('Author Name', get_default_author(),
  File "/home/nesffer/dev/nesffer.github.io/lektor/lektor/quickstart.py", line 137, in get_default_author
    return ent.pw_gecos.decode('utf-8', 'replace')
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by ChillarAnand** [comment]
lektor doesn't support Python 3 yet. Hopefully lektor 3 supports Python 3.

**Comment by nesffer** [comment]
Thank you for telling me.

I hope release `Lektor 3` ㅠㅠ

**Comment by niijv** [comment]
@Nesffer You can always support the effort for Python 3 support [here](https://github.com/lektor/lektor/issues/142).

**Comment by rhunwicks** [comment]
#142 is closed so I am assuming the Python 3 is now supported. However, this error still occurs - so this Issue should probably be reopened.

**Comment by rhunwicks** [comment]
Ignore my previous comment - Quickstart from Master does work, but Version 2.3 from pypi doesn't.
