### ISSUE TITLE
Not a directory when building certain files

### ISSUE THREAD

**Issue by milibopp** [lektor/lektor#227]
When building a certain set of files Lektor (version 2.2 on ArchLinux 64-bit) fails with the exception below:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/lektor/builder.py", line 796, in update
    yield ctx
  File "/usr/lib/python2.7/site-packages/lektor/builder.py", line 1037, in build_artifact
    build_func(artifact)
  File "/usr/lib/python2.7/site-packages/lektor/build_programs.py", line 260, in build_artifact
    with artifact.open('wb') as df:
  File "/usr/lib/python2.7/site-packages/lektor/builder.py", line 625, in open
    dir=os.path.dirname(self.dst_filename), prefix='.__trans')
  File "/usr/lib/python2.7/tempfile.py", line 314, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags)
  File "/usr/lib/python2.7/tempfile.py", line 244, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)
OSError: [Errno 20] Not a directory: '/home/eduard/.cache/lektor/builds/<OMITTEDHASH>/path/to/my-file-name/.__trans4eXxu0'
```

Looking at the cached output directory, you can see the reason for this error. In place of the directory (e.g. `my-file-name/index.html`) for my content item there is just a file (`my-file-name`), in which Lektor is trying to create the `.__trans4eXxu0` file. That obviously does not make sense, because it is not a directory. (But it should be?)

In addition, there is also a directory `_my-file-name` next to it, which contains the children content rendered correctly.

We are a bit lost and could use some pointers, as to why this might be happening? It seems like a bug in Lektor to me and it's hard to tell why it happens for some content files and not for others.

**Comment by mitsuhiko** [comment]
Do you have a testcase for this?

**Comment by milibopp** [comment]
Unfortunately nothing that I could share. I was hoping to get some insights about how to debug this issue and what causes the file/directory creation behaviour. That being said, I am not working on the particular piece of content that caused the issue any more.

**Comment by mitsuhiko** [comment]
I wonder if this might be a concurrency issue with the dev server.

**Comment by milibopp** [comment]
In that case it should happen randomly. That was not the case, it always affected the same files.
