### ISSUE TITLE
Error using quickstart on Python 2.7.x

### ISSUE THREAD

**Issue by ericmjl** [lektor/lektor#228]
After pulling in the `5714190` commit of lektor, I encountered a `UnicodeEncodeError` after running quickstart. I thought I'd raise the issue here for the benefit of those who might still be using Python 2.7.x.

```
That's all. Create project? [Y/n] 
Traceback (most recent call last):
  File "/Users/ericmjl/anaconda/envs/lektor/bin/lektor", line 9, in <module>
    load_entry_point('Lektor', 'console_scripts', 'lektor')()
  File "/Users/ericmjl/anaconda/envs/lektor/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/ericmjl/anaconda/envs/lektor/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/ericmjl/anaconda/envs/lektor/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ericmjl/anaconda/envs/lektor/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ericmjl/anaconda/envs/lektor/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/ericmjl/anaconda/envs/lektor/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/Users/ericmjl/anaconda/envs/lektor/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/ericmjl/Documents/github/lektor/lektor/cli.py", line 561, in quickstart_cmd
    project_quickstart(options)
  File "/Users/ericmjl/Documents/github/lektor/lektor/quickstart.py", line 217, in project_quickstart
    }, path)
  File "/Users/ericmjl/Documents/github/lektor/lektor/quickstart.py", line 125, in run
    f.write(rv + '\n')
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2014' in position 146: ordinal not in range(128)
(lektor)
```

I suspect it has to do with me using Python 2.7.11? Here's my `conda` environment right now:

```
(lektor)
ericmjl at dhcp-18-189-31-126 in ~/Documents/github/websites
$ conda list
# packages in environment at /Users/ericmjl/anaconda/envs/lektor:
#
argh                      0.26.2                    <pip>
babel                     2.3.4                     <pip>
cffi                      1.6.0                     <pip>
click                     6.6                       <pip>
cryptography              1.3.2                     <pip>
enum34                    1.1.6                     <pip>
exifread                  2.1.2                     <pip>
flask                     0.11                      <pip>
idna                      2.1                       <pip>
inifile                   0.3                       <pip>
ipaddress                 1.0.16                    <pip>
itsdangerous              0.24                      <pip>
jinja2                    2.8                       <pip>
lektor (/Users/ericmjl/Documents/github/lektor) 2.2                       <pip>
markupsafe                0.23                      <pip>
mistune                   0.7.2                     <pip>
ndg-httpsclient           0.4.0                     <pip>
openssl                   1.0.2h                        0    defaults
pathtools                 0.1.2                     <pip>
pip                       8.1.1                    py27_1    defaults
pyasn1                    0.1.9                     <pip>
pycparser                 2.14                      <pip>
pyopenssl                 16.0.0                    <pip>
python                    2.7.11                        0    defaults
pytz                      2016.4                    <pip>
pyyaml                    3.11                      <pip>
readline                  6.2                           2    defaults
requests                  2.10.0                    <pip>
setuptools                21.2.1                   py27_0    defaults
six                       1.10.0                    <pip>
sqlite                    3.13.0                        0    defaults
tk                        8.5.19                        0    conda-forge
watchdog                  0.8.3                     <pip>
werkzeug                  0.11.10                   <pip>
wheel                     0.29.0                   py27_0    defaults
zlib                      1.2.8                         3    conda-forge
```

When I created a new Python 3.5 environment, the error goes away, and Quickstart works as expected.

**Comment by arbonap** [comment]
The same error just happened to me. Any idea on where to begin to fix this?

**Comment by mitsuhiko** [comment]
Is this on master?

**Comment by go-bears** [comment]
I got this  same error using the development version. Does that help?

**Comment by go-bears** [comment]
And i'm using Ubuntu 14 and python 2.7
