### ISSUE TITLE
Source Code Syntax Highlighting

### ISSUE THREAD

**Issue by DaddyOh** [lektor/lektor#23]
I see that you highlight syntax in the documentation for lektor. I have copied a chunk of a template from the documentation to a blog page on a test site that I created for evaluating lektor and the same text does not get highlighted. 

How can syntax highlighting be enabled on lektor?

**Comment by item4** [comment]
[See this issue](https://github.com/lektor/lektor/issues/9#issuecomment-166419870)

**Comment by mitsuhiko** [comment]
So the main issue is that the current markdown library in Lektor is … not very good. It's the best I found but it's still impossible to extend.  So I did not document the API for extending it, but there are some plugins for it hidden in the lektor website repository.  I need to figure out what's the best way forward there.

**Comment by tylerlong** [comment]
highlight.js is good and simple to use. It could be pure frontend so you don't need to change any backend code.

I can provide your with some sample code if you decide to give it a try.

**Comment by mitsuhiko** [comment]
@tylerlong it's already implemented but i don't want to expose it yet until i have a solution for the markdown situation. Alternatively we will start to have plugins that depend on the current markdown specifics which might be messy. I will think about the best course of action.

**Comment by mitsuhiko** [comment]
Primarily I think the ticket should be called: figure out best and most extensible markdown library for Python.

**Comment by tylerlong** [comment]
@mitsuhiko If you are talking about markdown library, I happen to have some experience. I maintain an open source project here: https://github.com/tylingsoft/markdown-plus As far as I can tell, best markdown libraries are implemented in JS. (because markdown is mainly for generating html for the web where JS is dominating).

I highly recommend https://github.com/markdown-it/markdown-it. And if you want something feature-rich out-of-the-box, please ref my code here: https://github.com/tylingsoft/markdown-core/blob/master/markdown-core-node.js  It works on either server side or client side. Please kindly let me know if you need my help.

**Comment by mitsuhiko** [comment]
@tylerlong the server side runs Python and that library has to be a Python library. I will not start to depend on node just for markdown.

**Comment by item4** [comment]
Personally I like getlektor.com way(=plugin) now.

Because..
1. Not all sites needs syntax highlight.
2. plugin is editable and forkable.
3. this plugin use pygments, we can add lexer by customize or pr.

**Comment by tylerlong** [comment]
@mitsuhiko  I am sorry I didn't read the source code of this repo. Yesterday I read the official website https://www.getlektor.com/ and at the footer it mentions:

> Lektor at its core is a three clause BSD licensed Open Source project written in Python and Node.js.

I thought it already depended on node.  And that's the reason I suggested `markdown-it`. I just read the source code and didn't see any node code. So maybe it's not a good idea to bring more dependencies. :+1:

**Comment by mitsuhiko** [comment]
It uses node for the GUI only (and for invoking webpack).

**Comment by mitsuhiko** [comment]
Support for this is in this plugin now: https://github.com/lektor/lektor-markdown-highlighter

It uses an undocumented API which is not supported for anything other than official plugins because I really want to replace the markdown library with something better eventually.

**Comment by DaddyOh** [comment]
When I do 

``` bash
lektor plugins add markdown-highlighter
```

I get this stacktrace

``` bash
Traceback (most recent call last):
  File "/Applications/Lektor.app/Contents/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Applications/Lektor.app/Contents/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Applications/Lektor.app/Contents/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/lektor/uilink.py", line 47, in <module>
    main()
  File "/Applications/Lektor.app/Contents/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/lektor/uilink.py", line 43, in main
    main(prog_name='lektor')
  File "/Applications/Lektor.app/Contents/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Applications/Lektor.app/Contents/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Applications/Lektor.app/Contents/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Applications/Lektor.app/Contents/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Applications/Lektor.app/Contents/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Applications/Lektor.app/Contents/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Applications/Lektor.app/Contents/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/Applications/Lektor.app/Contents/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Applications/Lektor.app/Contents/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/lektor/cli.py", line 441, in plugins_add_cmd
    info = add_package_to_project(project, name)
  File "/Applications/Lektor.app/Contents/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/lektor/packages.py", line 48, in add_package_to_project
    rv = urllib.urlopen('https://pypi.python.org/pypi/%s/json' % choice)
  File "/Applications/Lektor.app/Contents/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/Applications/Lektor.app/Contents/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/Applications/Lektor.app/Contents/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 443, in open_https
    h.endheaders(data)
  File "/Applications/Lektor.app/Contents/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/Applications/Lektor.app/Contents/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/Applications/Lektor.app/Contents/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/Applications/Lektor.app/Contents/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1274, in connect
    server_hostname=server_hostname)
  File "/Applications/Lektor.app/Contents/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 352, in wrap_socket
    _context=self)
  File "/Applications/Lektor.app/Contents/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 579, in __init__
    self.do_handshake()
  File "/Applications/Lektor.app/Contents/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 808, in do_handshake
    self._sslobj.do_handshake()
IOError: [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
```

Environment
- Mac OS X 10.10.5
- Python 2.7.10

Thanks for working on this plugin.

**Comment by mitsuhiko** [comment]
I opened an issue for this @DaddyOh. Most likely you can just add this to your `.lektorproject` file instead:

``` ini
[packages]
lektor-markdown-highlighter = 0.1
```

**Comment by DaddyOh** [comment]
I've added:

``` ini
[packages]
lektor-markdown-highlighter = 0.1
```

And restarted lektor.  From the admin console I Refreshed the build. There is no package folder created in my project directory and of course no highlighting.

``` bash
lektor plugins flush-cache
lektor plugins list
```

Gives me

``` bash
Updating packages in /Users/epalmer/Library/Caches/Lektor/packages/02cd36ce0ecee50873189ecb0e272416 for project
Collecting lektor-markdown-highlighter==0.1
  Using cached lektor_markdown_highlighter-0.1-py2-none-any.whl
Collecting Pygments (from lektor-markdown-highlighter==0.1)
  Using cached Pygments-2.0.2-py2-none-any.whl
Installing collected packages: Pygments, lektor-markdown-highlighter
Successfully installed Pygments lektor-markdown-highlighter
markdown-highlighter (version 0.1)
```

And still no packages folder.

So I tried this

``` bash
lektor plugins reinstall
Force package cache refresh.
Updating packages in /Users/epalmer/Library/Caches/Lektor/packages/02cd36ce0ecee50873189ecb0e272416 for project
Collecting lektor-markdown-highlighter==0.1
  Using cached lektor_markdown_highlighter-0.1-py2-none-any.whl
Collecting Pygments (from lektor-markdown-highlighter==0.1)
  Using cached Pygments-2.0.2-py2-none-any.whl
Installing collected packages: Pygments, lektor-markdown-highlighter
Successfully installed Pygments lektor-markdown-highlighter
```

Same outcome.

**Comment by mitsuhiko** [comment]
@DaddyOh the message says that it was successfully installed. Read the documentation about how to get the stylesheets.  There is not supposed to be a package folder.

**Comment by DaddyOh** [comment]
Got it. Thanks.  Sorry should have read more. Thanks for your help.
