### ISSUE TITLE
Attachments with @ in filename break

### ISSUE THREAD

**Issue by chris-morgan** [lektor/lektor#245]
I tried to use a file named `foo@2x.png`, but Lektor broke on it:

```
Traceback (most recent call last):
  File "...\lektor\devserver.py", line 46, in build
    builder.update_all_source_infos()
  File "...\lektor\builder.py", line 1134, in update_all_source_infos
    self.extend_build_queue(to_build, prog)
  File "...\lektor\builder.py", line 1095, in extend_build_queue
    queue.extend(prog.iter_child_sources())
  File "...\lektor\db.py", line 1008, in __iter__
    for item in iterable:
  File "...\lektor\db.py", line 879, in _iterate
    if self._matches(record):
  File "...\lektor\db.py", line 849, in _matches
    if not self._include_undiscoverable and record.is_undiscoverable:
AttributeError: 'NoneType' object has no attribute 'is_undiscoverable'
```

I presume this is because of `@`’s status as a virtual marker, but with one part of the system accepting it as it is.

Not sure how conveniently anything can be done about it, but it is sad not to be able to use an `@` in a filename. Still more sad for it to break messily.

**Comment by mitsuhiko** [comment]
Not sure what I can do about this in general. I agree the exception should not be there but it would just be replaced with a slightly different exception :)
