### ISSUE TITLE
Windows platform installation issue

### ISSUE THREAD

**Issue by lyenliang** [lektor/lektor#27]
I'm using PowerShell to install lektor, the following is console output during installation:

```
PS C:\> iex ((new-object net.webclient).DownloadString('https://getlektor.com/install.ps1'))
Welcome to Lektor

This script will install Lektor on your computer.

   Installing at: C:\Users\lyenliang\AppData\Local\lektor-cli
Continue? [Yn] Y
New python executable in C:\Users\lyenliang\AppData\Local\lektor-cli\lib\Scripts\python.exe
Installing setuptools, pip, wheel...done.
Collecting Lektor
c:\users\lyenliang\appdata\local\lektor-cli\lib\lib\site-packages\pip\_vendor\requests\packages\urllib3\util\ssl_.py:90: I
nsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriat
ely and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/s
ecurity.html#insecureplatformwarning.
  InsecurePlatformWarning
  Using cached Lektor-1.0-py2-none-any.whl
Collecting Babel (from Lektor)
  Using cached Babel-2.1.1-py2.py3-none-any.whl
Collecting setuptools (from Lektor)
  Using cached setuptools-19.1.1-py2.py3-none-any.whl
Collecting Flask (from Lektor)
Collecting inifile (from Lektor)
  Using cached inifile-0.2-py2-none-any.whl
Collecting mistune (from Lektor)
  Using cached mistune-0.7.1-py2.py3-none-any.whl
Collecting click>=6.0 (from Lektor)
  Using cached click-6.2-py2.py3-none-any.whl
Collecting EXIFRead (from Lektor)
  Using cached ExifRead-2.1.2-py2-none-any.whl
Collecting watchdog (from Lektor)
Requirement already up-to-date: pip in c:\users\lyenliang\appdata\local\lektor-cli\lib\lib\site-packages (from Lektor)
Collecting Jinja2>=2.4 (from Lektor)
  Using cached Jinja2-2.8-py2.py3-none-any.whl
Collecting pytz>=0a (from Babel->Lektor)
  Using cached pytz-2015.7-py2.py3-none-any.whl
Collecting itsdangerous>=0.21 (from Flask->Lektor)
Collecting Werkzeug>=0.7 (from Flask->Lektor)
  Using cached Werkzeug-0.11.3-py2.py3-none-any.whl
Collecting argh>=0.24.1 (from watchdog->Lektor)
Collecting PyYAML>=3.10 (from watchdog->Lektor)
  Using cached PyYAML-3.11.tar.gz
Collecting pathtools>=0.1.1 (from watchdog->Lektor)
Collecting MarkupSafe (from Jinja2>=2.4->Lektor)
Building wheels for collected packages: PyYAML
  Running setup.py bdist_wheel for PyYAML
  Complete output from command c:\users\lyenliang\appdata\local\lektor-cli\lib\scripts\python.exe -c "import setuptools;__
file__='c:\\users\\lyenliang\\appdata\\local\\temp\\pip-build-qxh26z\\PyYAML\\setup.py';exec(compile(open(__file__).read()
.replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d c:\users\lyenliang\appdata\local\temp\tmpfdak1tpip-wheel-:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win32-2.7
  creating build\lib.win32-2.7\yaml
  copying lib\yaml\composer.py -> build\lib.win32-2.7\yaml
  copying lib\yaml\constructor.py -> build\lib.win32-2.7\yaml
  copying lib\yaml\cyaml.py -> build\lib.win32-2.7\yaml
  copying lib\yaml\dumper.py -> build\lib.win32-2.7\yaml
  copying lib\yaml\emitter.py -> build\lib.win32-2.7\yaml
  copying lib\yaml\error.py -> build\lib.win32-2.7\yaml
  copying lib\yaml\events.py -> build\lib.win32-2.7\yaml
  copying lib\yaml\loader.py -> build\lib.win32-2.7\yaml
  copying lib\yaml\nodes.py -> build\lib.win32-2.7\yaml
  copying lib\yaml\parser.py -> build\lib.win32-2.7\yaml
  copying lib\yaml\reader.py -> build\lib.win32-2.7\yaml
  copying lib\yaml\representer.py -> build\lib.win32-2.7\yaml
  copying lib\yaml\resolver.py -> build\lib.win32-2.7\yaml
  copying lib\yaml\scanner.py -> build\lib.win32-2.7\yaml
  copying lib\yaml\serializer.py -> build\lib.win32-2.7\yaml
  copying lib\yaml\tokens.py -> build\lib.win32-2.7\yaml
  copying lib\yaml\__init__.py -> build\lib.win32-2.7\yaml
  running build_ext
  creating build\temp.win32-2.7
  creating build\temp.win32-2.7\Release
  checking if libyaml is compilable
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "c:\users\lyenliang\appdata\local\temp\pip-build-qxh26z\PyYAML\setup.py", line 342, in <module>
      'test': test,
    File "C:\Python27\Lib\distutils\core.py", line 151, in setup
      dist.run_commands()
    File "C:\Python27\Lib\distutils\dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "C:\Python27\Lib\distutils\dist.py", line 972, in run_command
      cmd_obj.run()
    File "c:\users\lyenliang\appdata\local\lektor-cli\lib\lib\site-packages\wheel\bdist_wheel.py", line 175, in run
      self.run_command('build')
    File "C:\Python27\Lib\distutils\cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "C:\Python27\Lib\distutils\dist.py", line 972, in run_command
      cmd_obj.run()
    File "C:\Python27\Lib\distutils\command\build.py", line 127, in run
      self.run_command(cmd_name)
    File "C:\Python27\Lib\distutils\cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "C:\Python27\Lib\distutils\dist.py", line 972, in run_command
      cmd_obj.run()
    File "c:\users\lyenliang\appdata\local\temp\pip-build-qxh26z\PyYAML\setup.py", line 173, in run
      log.warn(str(exc))
  UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-6: ordinal not in range(128)

  ----------------------------------------
  Failed building wheel for PyYAML
Failed to build PyYAML
Installing collected packages: pytz, Babel, setuptools, itsdangerous, Werkzeug, MarkupSafe, Jinja2, Flask, inifile, mist
une, click, EXIFRead, argh, PyYAML, pathtools, watchdog, Lektor
  Found existing installation: setuptools 18.2
    Uninstalling setuptools-18.2:
      Successfully uninstalled setuptools-18.2
  Running setup.py install for PyYAML
    Complete output from command c:\users\lyenliang\appdata\local\lektor-cli\lib\scripts\python.exe -c "import setuptools,
 tokenize;__file__='c:\\users\\lyenliang\\appdata\\local\\temp\\pip-build-qxh26z\\PyYAML\\setup.py';exec(compile(getattr(t
okenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\lyenliang\app
data\local\temp\pip-qeykkj-record\install-record.txt --single-version-externally-managed --compile --install-headers c:\
users\lyenliang\appdata\local\lektor-cli\lib\include\site\python2.7\PyYAML:
    running install
    running build
    running build_py
    running build_ext
    checking if libyaml is compilable
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\lyenliang\appdata\local\temp\pip-build-qxh26z\PyYAML\setup.py", line 342, in <module>
        'test': test,
      File "C:\Python27\Lib\distutils\core.py", line 151, in setup
        dist.run_commands()
      File "C:\Python27\Lib\distutils\dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "C:\Python27\Lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "c:\users\lyenliang\appdata\local\lektor-cli\lib\lib\site-packages\setuptools\command\install.py", line 61, in
run
        return orig.install.run(self)
      File "C:\Python27\Lib\distutils\command\install.py", line 563, in run
        self.run_command('build')
      File "C:\Python27\Lib\distutils\cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "C:\Python27\Lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "C:\Python27\Lib\distutils\command\build.py", line 127, in run
        self.run_command(cmd_name)
      File "C:\Python27\Lib\distutils\cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "C:\Python27\Lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "c:\users\lyenliang\appdata\local\temp\pip-build-qxh26z\PyYAML\setup.py", line 173, in run
        log.warn(str(exc))
    UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-6: ordinal not in range(128)

    ----------------------------------------
Command "c:\users\lyenliang\appdata\local\lektor-cli\lib\scripts\python.exe -c "import setuptools, tokenize;__file__='c:\\
users\\lyenliang\\appdata\\local\\temp\\pip-build-qxh26z\\PyYAML\\setup.py';exec(compile(getattr(tokenize, 'open', open)(_
_file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\lyenliang\appdata\local\temp\pip-qeyk
kj-record\install-record.txt --single-version-externally-managed --compile --install-headers c:\users\lyenliang\appdata\lo
cal\lektor-cli\lib\include\site\python2.7\PyYAML" failed with error code 1 in c:\users\lyenliang\appdata\local\temp\pip-bu
ild-qxh26z\PyYAML
c:\users\lyenliang\appdata\local\lektor-cli\lib\lib\site-packages\pip\_vendor\requests\packages\urllib3\util\ssl_.py:90: I
nsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriat
ely and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/s
ecurity.html#insecureplatformwarning.
  InsecurePlatformWarning
```

The error `UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-6` seems to be a problem of PyYAML. 

I wish I could view the content of `c:\users\lyenliang\appdata\local\temp\pip-build-qxh26z\PyYAML\setup.py`, but the file doesn't exist after the installation script. 

Does anyone have an idea about how to solve this problem?

**Comment by mitsuhiko** [comment]
That's a bug in PyYAML it seems. I'm surprised it gets that error because the exception it tries to log should have a bytestring representation.  Can you do me a favor and help me debug this?

Can you add this to line 172/173:

``` python
print repr(exc)
print repr(exc.__dict__)
```

And then run it again and paste the output.

**Comment by lyenliang** [comment]
I downloaded `PyYAML-3.11.zip` from `http://pyyaml.org/wiki/PyYAML`
-> install PyYAML with `python setup.py install` 
-> then I found that PyYAML is successfully installed on my computer, no error is reported

I couldn't reproduce the bug with the above methods. 

Can you guide me on how to add new code to PyYAML/setup.py ? 

`c:\users\lyenliang\appdata\local\temp\pip-build-qxh26z\PyYAML\setup.py` doesn't exist after running the installation script.

Maybe the bug has something to do with my Chinese Windows operating system.

**Comment by mitsuhiko** [comment]
So if `setup.py install` works, can you try what happens if you do `pip install PyYAML-3.11.zip`?

**Comment by niijv** [comment]
Another question, do you have any version of Visual Studio on your computer?

**Comment by lyenliang** [comment]
I tried to uninstall PyYAML first by `pip --verbose uninstall PyYAML-3.11.zip`, deleting `PyYAML-3.11-py2.7.egg-info` folder under `C:\Python27\Lib\site-packages`.

I'm not sure if PyYAML is really uninstalled from my computer. Because `pip --verbose uninstall` didn't give me any response.

Then I use `pip --verbose install PyYAML-3.11.zip` to install PyYAML:

```
D:\Softwares>pip --verbose install PyYAML-3.11.zip
Processing d:\softwares\pyyaml-3.11.zip
Running setup.py (path:c:\users\lyenliang\appdata\local\temp\pip-irvoza-build\setup.py) egg_info for package from file:///D:/Softwares/PyYAML-3.11.zip
Running command python setup.py egg_info
running egg_info
creating pip-egg-info\PyYAML.egg-info
writing pip-egg-info\PyYAML.egg-info\PKG-INFO
writing top-level names to pip-egg-info\PyYAML.egg-info\top_level.txt
writing dependency_links to pip-egg-info\PyYAML.egg-info\dependency_links.txt
writing manifest file 'pip-egg-info\PyYAML.egg-info\SOURCES.txt'
warning: manifest_maker: standard file '-c' not found

reading manifest file 'pip-egg-info\PyYAML.egg-info\SOURCES.txt'
writing manifest file 'pip-egg-info\PyYAML.egg-info\SOURCES.txt'
Source in c:\users\lyenliang\appdata\local\temp\pip-irvoza-build has version 3.1
1, which satisfies requirement PyYAML==3.11 from file:///D:/Softwares/PyYAML-3.1
1.zip
Installing collected packages: PyYAML
Running setup.py install for PyYAML
Running command c:\python27\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\lyenliang\\appdata\\local\\temp\\pip-irvoza-build\\setup.py';exec(
compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\lyenliang\appdata\local\temp\pip-qfc
fbz-record\install-record.txt --single-version-externally-managed --compile
running install
running build
running build_py
creating build
creating build\lib.win32-2.7
creating build\lib.win32-2.7\yaml
copying lib\yaml\composer.py -> build\lib.win32-2.7\yaml
copying lib\yaml\constructor.py -> build\lib.win32-2.7\yaml
copying lib\yaml\cyaml.py -> build\lib.win32-2.7\yaml
copying lib\yaml\dumper.py -> build\lib.win32-2.7\yaml
copying lib\yaml\emitter.py -> build\lib.win32-2.7\yaml
copying lib\yaml\error.py -> build\lib.win32-2.7\yaml
copying lib\yaml\events.py -> build\lib.win32-2.7\yaml
copying lib\yaml\loader.py -> build\lib.win32-2.7\yaml
copying lib\yaml\nodes.py -> build\lib.win32-2.7\yaml
copying lib\yaml\parser.py -> build\lib.win32-2.7\yaml
copying lib\yaml\reader.py -> build\lib.win32-2.7\yaml
copying lib\yaml\representer.py -> build\lib.win32-2.7\yaml
copying lib\yaml\resolver.py -> build\lib.win32-2.7\yaml
copying lib\yaml\scanner.py -> build\lib.win32-2.7\yaml
copying lib\yaml\serializer.py -> build\lib.win32-2.7\yaml
copying lib\yaml\tokens.py -> build\lib.win32-2.7\yaml
copying lib\yaml\__init__.py -> build\lib.win32-2.7\yaml
running build_ext
creating build\temp.win32-2.7
creating build\temp.win32-2.7\Release
checking if libyaml is compilable
C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Ic:\python27\include -Ic:\python27\PC /Tcbuild\temp.win32-2.7\Release\check_libyaml.c /Fobuild\temp.win32-2.7\Release\check_libyaml.obj
check_libyaml.c
build\temp.win32-2.7\Release\check_libyaml.c(2) : fatal error C1083: Cannot open include file: 'yaml.h': No such file or directory

libyaml is not found or a compiler error: forcing --without-libyaml
(if libyaml is installed correctly, you may need to
 specify the option --include-dirs or uncomment and
 modify the parameter include_dirs in setup.cfg)
running install_lib
copying build\lib.win32-2.7\yaml\composer.py -> c:\python27\Lib\site-packages\yaml
copying build\lib.win32-2.7\yaml\constructor.py -> c:\python27\Lib\site-packages\yaml
copying build\lib.win32-2.7\yaml\cyaml.py -> c:\python27\Lib\site-packages\yaml
copying build\lib.win32-2.7\yaml\dumper.py -> c:\python27\Lib\site-packages\yaml
copying build\lib.win32-2.7\yaml\emitter.py -> c:\python27\Lib\site-packages\yaml
copying build\lib.win32-2.7\yaml\error.py -> c:\python27\Lib\site-packages\yaml
copying build\lib.win32-2.7\yaml\events.py -> c:\python27\Lib\site-packages\yaml
copying build\lib.win32-2.7\yaml\loader.py -> c:\python27\Lib\site-packages\yaml
copying build\lib.win32-2.7\yaml\nodes.py -> c:\python27\Lib\site-packages\yaml
copying build\lib.win32-2.7\yaml\parser.py -> c:\python27\Lib\site-packages\yaml
copying build\lib.win32-2.7\yaml\reader.py -> c:\python27\Lib\site-packages\yaml
copying build\lib.win32-2.7\yaml\representer.py -> c:\python27\Lib\site-packages\yaml
copying build\lib.win32-2.7\yaml\resolver.py -> c:\python27\Lib\site-packages\yaml
copying build\lib.win32-2.7\yaml\scanner.py -> c:\python27\Lib\site-packages\yaml
copying build\lib.win32-2.7\yaml\serializer.py -> c:\python27\Lib\site-packages\yaml
copying build\lib.win32-2.7\yaml\tokens.py -> c:\python27\Lib\site-packages\yaml
copying build\lib.win32-2.7\yaml\__init__.py -> c:\python27\Lib\site-packages\yaml
byte-compiling c:\python27\Lib\site-packages\yaml\composer.py to composer.pyc
byte-compiling c:\python27\Lib\site-packages\yaml\constructor.py to constructor.pyc
byte-compiling c:\python27\Lib\site-packages\yaml\cyaml.py to cyaml.pyc
byte-compiling c:\python27\Lib\site-packages\yaml\dumper.py to dumper.pyc
byte-compiling c:\python27\Lib\site-packages\yaml\emitter.py to emitter.pyc
byte-compiling c:\python27\Lib\site-packages\yaml\error.py to error.pyc
byte-compiling c:\python27\Lib\site-packages\yaml\events.py to events.pyc
byte-compiling c:\python27\Lib\site-packages\yaml\loader.py to loader.pyc
byte-compiling c:\python27\Lib\site-packages\yaml\nodes.py to nodes.pyc
byte-compiling c:\python27\Lib\site-packages\yaml\parser.py to parser.pyc
byte-compiling c:\python27\Lib\site-packages\yaml\reader.py to reader.pyc
byte-compiling c:\python27\Lib\site-packages\yaml\representer.py to representer.pyc
byte-compiling c:\python27\Lib\site-packages\yaml\resolver.py to resolver.pyc
byte-compiling c:\python27\Lib\site-packages\yaml\scanner.py to scanner.pyc
byte-compiling c:\python27\Lib\site-packages\yaml\serializer.py to serializer.pyc
byte-compiling c:\python27\Lib\site-packages\yaml\tokens.py to tokens.pyc
byte-compiling c:\python27\Lib\site-packages\yaml\__init__.py to __init__.pyc
running install_egg_info
running egg_info
creating lib\PyYAML.egg-info
writing lib\PyYAML.egg-info\PKG-INFO
writing top-level names to lib\PyYAML.egg-info\top_level.txt
writing dependency_links to lib\PyYAML.egg-info\dependency_links.txt
writing manifest file 'lib\PyYAML.egg-info\SOURCES.txt'
warning: manifest_maker: standard file '-c' not found

reading manifest file 'lib\PyYAML.egg-info\SOURCES.txt'
writing manifest file 'lib\PyYAML.egg-info\SOURCES.txt'
Copying lib\PyYAML.egg-info to c:\python27\Lib\site-packages\PyYAML-3.11-py2.7.egg-info
running install_scripts
writing list of installed files to 'c:\users\lyenliang\appdata\local\temp\pip-qfcfbz-record\install-record.txt'
Removing source in c:\users\lyenliang\appdata\local\temp\pip-irvoza-build
Successfully installed PyYAML-3.11
Cleaning up...
```

It looks like there is something wrong during the installation.

**Comment by lyenliang** [comment]
@niijv  
I have Visual Studio 2005 and Visual Studio 2008 installed on my computer.

**Comment by lyenliang** [comment]
Now I reinstall lektor by
1. Removing `lektor-cli` folder under `C:\Users\lyenliang\AppData\Local`
2. Removing PyYAML by `pip --verbose uninstall PyYAML-3.11.zip`, deleting `PyYAML-3.11-py2.7.egg-info` folder under `C:\Python27\Lib\site-packages`, hoping to reproduce this issue.
3. Typing `iex ((new-object net.webclient).DownloadString('https://getlektor.com/install.ps1'))
   Welcome to Lektor` under PowerShell

But I found I can successfully install lektor:

```
PS C:\> iex ((new-object net.webclient).DownloadString('https://getlektor.com/install.ps1'))
Welcome to Lektor

This script will install Lektor on your computer.

   Installing at: C:\Users\lyenliang\AppData\Local\lektor-cli
Continue? [Yn] Welcome to Lektor
Continue? [Yn] Y
New python executable in C:\Users\lyenliang\AppData\Local\lektor-cli\lib\Scripts\python.exe
Installing setuptools, pip, wheel...done.
Collecting Lektor
  Using cached Lektor-1.0-py2-none-any.whl
Collecting Babel (from Lektor)
  Using cached Babel-2.1.1-py2.py3-none-any.whl
Collecting setuptools (from Lektor)
  Using cached setuptools-19.1.1-py2.py3-none-any.whl
Collecting Flask (from Lektor)
Collecting inifile (from Lektor)
  Using cached inifile-0.2-py2-none-any.whl
Collecting mistune (from Lektor)
  Using cached mistune-0.7.1-py2.py3-none-any.whl
Collecting click>=6.0 (from Lektor)
  Using cached click-6.2-py2.py3-none-any.whl
Collecting EXIFRead (from Lektor)
  Using cached ExifRead-2.1.2-py2-none-any.whl
Collecting watchdog (from Lektor)
Requirement already up-to-date: pip in c:\users\lyenliang\appdata\local\lektor-cli\lib\lib\site-packages (from Lektor)
Collecting Jinja2>=2.4 (from Lektor)
  Using cached Jinja2-2.8-py2.py3-none-any.whl
Collecting pytz>=0a (from Babel->Lektor)
  Using cached pytz-2015.7-py2.py3-none-any.whl
Collecting itsdangerous>=0.21 (from Flask->Lektor)
Collecting Werkzeug>=0.7 (from Flask->Lektor)
  Using cached Werkzeug-0.11.3-py2.py3-none-any.whl
Collecting argh>=0.24.1 (from watchdog->Lektor)
Collecting PyYAML>=3.10 (from watchdog->Lektor)
Collecting pathtools>=0.1.1 (from watchdog->Lektor)
Collecting MarkupSafe (from Jinja2>=2.4->Lektor)
Installing collected packages: pytz, Babel, setuptools, itsdangerous, Werkzeug, MarkupSafe, Jinja2, Flask, inifile, mist
une, click, EXIFRead, argh, PyYAML, pathtools, watchdog, Lektor
  Found existing installation: setuptools 18.2
    Uninstalling setuptools-18.2:
      Successfully uninstalled setuptools-18.2
Successfully installed Babel-2.1.1 EXIFRead-2.1.2 Flask-0.10.1 Jinja2-2.8 Lektor-1.0 MarkupSafe-0.23 PyYAML-3.11 Werkzeu
g-0.11.3 argh-0.26.1 click-6.2 inifile-0.2 itsdangerous-0.24 mistune-0.7.1 pathtools-0.1.2 pytz-2015.7 setuptools-19.1.1
 watchdog-0.8.3

All done!
```

This time `Using cached PyYAML-3.11.tar.gz` doesn't show up. What does that mean?

Is there anything wrong my reinstallation?

**Comment by niijv** [comment]
Lektor generally installs everything in its own virtualenv at `C:\Users\lyenliang\AppData\Local\lektor-cli\lib` (in your case), so it would not conflict with your install in `C:\Python27\site-packages` but maybe the uninstall of  PyYAML in `C:\Python27` removed the cache?

**Comment by niijv** [comment]
But your installation seems to  have worked fine, try  `lektor quickstart` for example and play around a bit.

**Comment by lyenliang** [comment]
Thank you. My problem is gone. Though I don't know what happened to my computer.
