### ISSUE TITLE
TypeError on deploy with RSync

### ISSUE THREAD

**Issue by severen** [lektor/lektor#277]
I keep getting the following when trying to deploy my website using RSync:

```
Deploying to Production
  Build cache: /home/shrike/.cache/lektor/builds/4fd9ee3226aa058bcb423a945285f38c
  Target: rsync://192.168.1.3/var/www/shrike.me/newblog
Traceback (most recent call last):
  File "/home/shrike/.local/share/virtualenvs/website/bin/lektor", line 11, in <module>
    load_entry_point('Lektor', 'console_scripts', 'lektor')()
  File "/home/shrike/.local/share/virtualenvs/website/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/shrike/.local/share/virtualenvs/website/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/shrike/.local/share/virtualenvs/website/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/shrike/.local/share/virtualenvs/website/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/shrike/.local/share/virtualenvs/website/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/shrike/.local/share/virtualenvs/website/lib/python3.5/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/shrike/.local/share/virtualenvs/website/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/shrike/Documents/Projects/website/lektor/lektor/cli.py", line 301, in deploy_cmd
    for line in event_iter:
  File "/home/shrike/Documents/Projects/website/lektor/lektor/publisher.py", line 231, in publish
    client = self.get_command(target_url, tempdir, credentials)
  File "/home/shrike/Documents/Projects/website/lektor/lektor/publisher.py", line 223, in get_command
    target.append(':' + target_url.path.encode('utf-8').rstrip('/') + '/')
TypeError: a bytes-like object is required, not 'str'
```

Perhaps this is part of the code where Python 3 support is incomplete?

**Extra Info:**
- Python version: 3.5.2
- OS: Arch Linux.
- Lektor is installed inside of a VirtualEnv by itself, with no other packages apart from its dependencies.

**Comment by truenicoco** [comment]
It had been a while since I had not updated my website, but I had the same error with lektor from fedora 31 official packages:

```
Traceback (most recent call last):
  File "/usr/bin/lektor", line 11, in <module>
    load_entry_point('Lektor==3.0.1', 'console_scripts', 'lektor')()
  File "/usr/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/lektor/cli.py", line 301, in deploy_cmd
    for line in event_iter:
  File "/usr/lib/python3.7/site-packages/lektor/publisher.py", line 231, in publish
    client = self.get_command(target_url, tempdir, credentials)
  File "/usr/lib/python3.7/site-packages/lektor/publisher.py", line 223, in get_command
    target.append(':' + target_url.path.encode('utf-8').rstrip('/') + '/')
TypeError: a bytes-like object is required, not 'str'
```

Installing lektor "the curl way" does not work on this fedora 31 box either:
```
> curl -sf https://www.getlektor.com/install.sh | sh


Welcome to Lektor

This script will install Lektor on your computer.

Installing at:
  bin: /home/ncedilni/.local/bin
  app: /home/ncedilni/.local/lib/lektor

Continue? [Yn] Y
/usr/bin/python: can't open file './src/virtualenv.py': [Errno 2] No such file or directory
/usr/bin/python: can't open file './virtualenv.py': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "<stdin>", line 151, in <module>
  File "<stdin>", line 146, in main
  File "<stdin>", line 110, in install
  File "/usr/lib64/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/ncedilni/.local/lib/lektor/bin/pip': '/home/ncedilni/.local/lib/lektor/bin/pip'
```

**Comment by xlotlu** [comment]
@truenicoco the "curl way" has been updated, it didn't make it to the website yet. Do
```
curl https://raw.githubusercontent.com/lektor/lektor-website/master/assets/installer.py | python3
```
instead.
