### ISSUE TITLE
Thumbnails not copied correctly

### ISSUE THREAD

**Issue by toxinu** [lektor/lektor#30]
I think my attachment thumbnails are not copied at all.

**models/project.ini**:

``` ini
[model]
name = Project
label = {{ this.name }}

[fields.cover]
label = Cover
type = select
source = record.attachments.images
```

**templates/project.html**:

``` jinja
{% for project in site.query('/projects') %}
  <img src="{{ project.attachments.images.get(project.cover).thumbnail(263)|url }}">
{% endfor %
```

**Rendered html**:

```
<img src="./projects/my-project/image_1@263.jpg">
```

Error at `lektor build -v` (more debug don't give more information):

``` python
U projects/my-project/image_1@640.jpg
  E projects/my-project/image_1@640.jpg (TypeError: argument of type 'NoneType' is not iterable)
```

Lektor version: `1.0`

**Comment by mitsuhiko** [comment]
This most likely is an issue elsewhere but hard to tell because the traceback is not shown.  I opened up an issue for this.

**Comment by toxinu** [comment]
Ok. Let's wait to have enough information in verbose to investigate it. :+1:

**Comment by mitsuhiko** [comment]
If you use the dev version of either master or the 1.1 branch you should be able to figure out now :)

**Comment by mitsuhiko** [comment]
Closing as invalid. If still relevant please reopen.

**Comment by toxinu** [comment]
Sorry for being late. I'm here with more information!
This is output for `lektor build -vvv` (d5152f518e791c372ce3a78460e6cb164375d44d):

``` python
Source <Page model=u'project' path=u'/projects/my-project'>
  U projects/my-project/index.html
    build program: lektor.build_programs.PageBuildProgram
    sub artifact: projects/my-project/image_thumb@640.jpg
    sub artifact: projects/my-project/image_1@640.jpg
  U projects/my-project/image_1@640.jpg
    build program: lektor.imagetools.build_thumbnail_artifact
    E projects/my-project/image_1@640.jpg (TypeError: argument of type 'NoneType' is not iterable)
      Traceback (most recent call last):
        File "<path>/lektor/lektor/builder.py", line 702, in update
          yield ctx
        File "<path>/lektor/lektor/builder.py", line 926, in build_artifact
          build_func(artifact)
        File "<path>/lektor/lektor/imagetools.py", line 331, in build_thumbnail_artifact
          portable_popen(cmdline).wait()
        File "<path>/lektor/lektor/utils.py", line 424, in portable_popen
          exe = locate_executable(cmd[0], kwargs.get('cwd'))
        File "<path>/lektor/lektor/utils.py", line 218, in locate_executable
          if os.path.sep in exe_file or \
      TypeError: argument of type 'NoneType' is not iterable
  forcing sources dirty: True

```

New issue or reopening it ?

**Comment by mitsuhiko** [comment]
@socketubs that happens if you do not have imagemagick installed. I will make this into a better error message.
