### ISSUE TITLE
”Attempted relative import in non-package“ with  LEKTOR_DEV=1

### ISSUE THREAD

**Issue by uranusjr** [lektor/lektor#341]
On macOS 10.11.6 using the official Lektor.app 2.3.

```
$ export LEKTOR_DEV=1
$ lektor server
 * Project path: /my.lektorproject
 * Output path: /Users/uranusjr/Library/Caches/Lektor/builds/979f1fa3702bf114cceebb0535d1774b
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with fsevents reloader
Traceback (most recent call last):
  File "/Applications/Lektor.app/Contents/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/lektor/uilink.py", line 47, in <module>
    main()
  File "/Applications/Lektor.app/Contents/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/lektor/uilink.py", line 42, in main
    from .cli import main
ValueError: Attempted relative import in non-package
```

**Comment by xlotlu** [comment]
@uranusjr it's been a long time, and also there is no Lektor.app anymore. Could you test that this is still the case?

**Comment by uranusjr** [comment]
No idea, TBH; I switched away from using Lektor.app shortly afterwards. I’ll close this; someone can always file another issue if this is still a problem.
