### ISSUE TITLE
`Context.sub_artifact` missing sources

### ISSUE THREAD

**Issue by b4stien** [lektor/lektor#353]
Reading the docs (https://www.getlektor.com/docs/api/build/context/sub-artifact/) I was under the impression that the `sources` argument was optional, however if I try to add a sub artifact without giving one it I get an error (this is with master, it also happens with the last release):

```
Traceback (most recent call last):
  File "/somepath/lib/python2.7/site-packages/lektor/devserver.py", line 47, in build
    builder.build_all()
  File "/somepath/lib/python2.7/site-packages/lektor/builder.py", line 1128, in build_all
    prog, build_state = self.build(source, path_cache=path_cache)
  File "/somepath/lib/python2.7/site-packages/lektor/builder.py", line 1098, in build
    prog.build()
  File "/somepath/lib/python2.7/site-packages/lektor/build_programs.py", line 107, in build
    _build(artifact, build_func)
  File "/somepath/lib/python2.7/site-packages/lektor/build_programs.py", line 91, in _build
    ctx = gen.build_artifact(artifact, build_func)
  File "/somepath/lib/python2.7/site-packages/lektor/builder.py", line 1058, in build_artifact
    build_func(artifact)
  File "/Users/bastien/.pyenv/versions/2.7.13/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/somepath/lib/python2.7/site-packages/lektor/builder.py", line 803, in update
    self.finish_update(ctx)
  File "/somepath/lib/python2.7/site-packages/lektor/builder.py", line 863, in finish_update
    ctx.referenced_virtual_dependencies.values())
  File "/somepath/lib/python2.7/site-packages/lektor/builder.py", line 738, in _memorize_dependencies
    self._auto_deferred_update_operation(operation)
  File "/somepath/lib/python2.7/site-packages/lektor/builder.py", line 783, in _auto_deferred_update_operation
    f(con)
  File "/somepath/lib/python2.7/site-packages/lektor/builder.py", line 668, in operation
    for x in self.sources)
TypeError: 'NoneType' object is not iterable
```

I can get it to work by explicitly passing a source filename with (for instance):

```
ctx = get_ctx()

def build_artifact(artifact):
    # Do stuff
    pass

ctx.add_sub_artifact(
    '/a/path',
    build_func=build_artifact,
    sources=[ctx.source.source_filename],
)
```

**Comment by nixjdm** [comment]
You're completely right. The docs do indicate that you should be able to create an artifact with no listed `sources`; with just an `artifact_name`. This doesn't actually work. If you call `sub_artifact` while neglecting to provide `sources`, you get that traceback.

That line throwing the exception is not the only one that makes this not work. The code isn't set up completely to handle this case. The docs indicate a fallback, which doesn't work. Instead, I think they should indicate a reasonable source to provide [within a plugin], but allow actually having no source at all.

Tangentially related: https://github.com/lektor/lektor-markdown-highlighter/issues/7
