### ISSUE TITLE
Non-ascii characters in project name raises UnicodeDecodeError

### ISSUE THREAD

**Issue by JoseTomasTocino** [lektor/lektor#36]
After using `lektor quickstart`, if you use a _Project Name_  with non ascii characters (such as `áá`), the installation fails with:

``` pytb
Traceback (most recent call last):
  File "/home/jose/.virtualenvs/lektor/bin/lektor", line 11, in <module>
    sys.exit(main())
  File "/home/jose/.virtualenvs/lektor/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/jose/.virtualenvs/lektor/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/jose/.virtualenvs/lektor/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jose/.virtualenvs/lektor/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jose/.virtualenvs/lektor/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/jose/.virtualenvs/lektor/local/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/jose/.virtualenvs/lektor/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/jose/.virtualenvs/lektor/local/lib/python2.7/site-packages/lektor/cli.py", line 548, in quickstart_cmd
    project_quickstart(options)
  File "/home/jose/.virtualenvs/lektor/local/lib/python2.7/site-packages/lektor/quickstart.py", line 200, in project_quickstart
    }, path)
  File "/home/jose/.virtualenvs/lektor/local/lib/python2.7/site-packages/lektor/quickstart.py", line 119, in run
    f.write(rv.encode('utf-8') + '\n')
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/home/jose/.virtualenvs/lektor/local/lib/python2.7/site-packages/lektor/quickstart.py", line 96, in make_target_directory
    os.path.join(path, filename))
  File "/home/jose/.virtualenvs/lektor/lib/python2.7/posixpath.py", line 80, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)
```

Using non-ascii characters in any of the other fields (including _Project Path_) does _not_ raise any exception.

**Comment by mitsuhiko** [comment]
Non ascii characters are unsupported in filenames.  It's not quite clear how supporting this would work.  There are a bunch of really frustrating problems with them that make supporting them really, really tricky.

**Comment by mitsuhiko** [comment]
To elaborate on this a bit more: the idea is that a lektor project can work on different operating systems and web servers.  However there is no agreed upon standard for mapping filesystem characters to URLs that works everywhere.  It works in a way on Linux and OSX if you assume utf-8 everywhere but even there the system plays tricks on you. OSX will re-normalize all filenames to something which is totally unexpected :(

So supporting this would need a ton of tooling support which I'm not really willing to do myself but if someone feels strongly about this support is very much appreciated.  Likewise better errors for this for the moment.

**Comment by JoseTomasTocino** [comment]
The main problem here (for me, at least) is that the exception is raised when I use a **Project Name** with ascii characters, regardless of the _Project Path_. In fact, I can use non-ascii characters for the _Project Path_ and there's no problem. 

The problem arises in the `Generator.make_target_directory` function when the context manager is getting released. Could you explain the rationale behind creating a temporary folder and then moving all the files to the final output folder? I've modified the function to directly `yield path` and skip the generation and subsequent removal of the `scratch` folder, and it works ok.

**Comment by mitsuhiko** [comment]
I will investigate.  To answer your question:

> Could you explain the rationale behind creating a temporary folder and then moving all the files to the final output folder?

Ensures that if an exception happens it does not leave garbage behind.

**Comment by moschlar** [comment]
The actual exception comes from moving the ''<Project Name>.lektorproject'' file...
It look as if it can be renamed (to anything ''*.lektorproject'') and building then works fine (the project name itself is set from an entry in that file).

``` shell-session
moschlar@thinkmo ~/www/taest $ lektor project-info
Name: Täst
File: /home/moschlar/www/taest/taest.lektorproject
Tree: /home/moschlar/www/taest
Output: /home/moschlar/.cache/lektor/builds/e2c64af1142ff2081c5365962adde006
```

So maybe for this specific problem it would be sufficient to just use a slugified filename for the ''.lektorproject'' file?

**Comment by mitsuhiko** [comment]
I can just fix it so that the project folder itself can contain unicode characters :)

**Comment by mitsuhiko** [comment]
This was not supposed to be closed yet. Merge failure.

**Comment by mitsuhiko** [comment]
Fixed now.
