### ISSUE TITLE
JS error in admin on pages w/ complex model

### ISSUE THREAD

**Issue by ulope** [lektor/lektor#376]
Since upgrading to latest master I receive the following error on subpages with complex models with lots of nested flowblocks:
<details>
<summary><img src="https://ds.ulo.pe/401D8WGD5W.png"></summary>
<pre>
Uncaught (in promise) TypeError: Cannot read property 'props' of undefined
    at Object.renderFormField (eval at <anonymous> (http://localhost:5000/admin/static/gen/app.js:656:2), <anonymous>:262:30)
    at Array.map (native)
    at eval (eval at <anonymous> (http://localhost:5000/admin/static/gen/app.js:626:2), <anonymous>:245:11)
    at Array.forEach (native)
    at Object.renderFieldRows (eval at <anonymous> (http://localhost:5000/admin/static/gen/app.js:626:2), <anonymous>:237:8)
    at eval (eval at <anonymous> (http://localhost:5000/admin/static/gen/app.js:656:2), <anonymous>:287:28)
    at Array.map (native)
    at Object.renderBlocks (eval at <anonymous> (http://localhost:5000/admin/static/gen/app.js:656:2), <anonymous>:281:29)
    at Object.render (eval at <anonymous> (http://localhost:5000/admin/static/gen/app.js:656:2), <anonymous>:382:12)
    at eval (eval at <anonymous> (http://localhost:5000/admin/static/gen/vendor.js:877:2), <anonymous>:796:21)
</pre>
</details>

I haven't yet been able to figured out what exactly triggers this.

In case anyone is motivated to look into this the problem happens on all pages in [ulope/pyformat.info@v2](https://github.com/ulope/pyformat.info/tree/v2) that use the `example` model (e.g. everything below `content/examples/`)

**Comment by nixjdm** [comment]
I think this was actually fixed by https://github.com/lektor/lektor/pull/427.
