### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec .... character maps to <undefined>

### ISSUE THREAD

**Issue by mickn277** [lektor/lektor#378]
Steps to reproduce

Python 3.6 installed to C:\apps\Python\Python36\ on Windows 10 64Bit ...

CMD>
cd \tmp
pip install lektor
lektor quickstart --path example-project

Traceback (most recent call last):
  File "C:\apps\Python\Python36\Scripts\lektor-script.py", line 11, in <module>
    load_entry_point('Lektor==2.3', 'console_scripts', 'lektor')()
  File "c:\apps\python\python36\lib\site-packages\pkg_resources\__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\apps\python\python36\lib\site-packages\pkg_resources\__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "c:\apps\python\python36\lib\site-packages\pkg_resources\__init__.py", line 2291, in load
    return self.resolve()
  File "c:\apps\python\python36\lib\site-packages\pkg_resources\__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\apps\python\python36\lib\site-packages\lektor\cli.py", line 8, in <module>
    from .i18n import get_default_lang, is_valid_language
  File "c:\apps\python\python36\lib\site-packages\lektor\i18n.py", line 16, in <module>
    translations[_lang] = json.load(f)
  File "c:\apps\python\python36\lib\json\__init__.py", line 296, in load
    return loads(fp.read(),
  File "c:\apps\python\python36\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 693: character maps to <undefined>

**Comment by nixjdm** [comment]
Can you try this again with Lektor 3.0.1? It was released after you posted this issue. Lektor was not compatible with Python 3 at Lektor==2.3, but it should be compatible with Python 3.5 at least as of Lektor==3.0.1.

**Comment by goanpeca** [comment]
@nixjdm seeing this issue when building the conda package as well with 3.0.1

https://ci.appveyor.com/project/conda-forge/lektor-feedstock/build/1.0.15/job/j420g2jjx70dg7j8

```
(C:\bld\lektor_1499821169310\_t_env) (root) C:\bld\lektor_1499821169310\test_tmp>lektor --help 
Traceback (most recent call last):
  File "C:\bld\lektor_1499821169310\_t_env\Scripts\lektor-script.py", line 3, in <module>
    import lektor.cli
  File "C:\bld\lektor_1499821169310\_t_env\lib\site-packages\lektor\cli.py", line 8, in <module>
    from .i18n import get_default_lang, is_valid_language
  File "C:\bld\lektor_1499821169310\_t_env\lib\site-packages\lektor\i18n.py", line 17, in <module>
    translations[_lang] = json.load(f)
  File "C:\bld\lektor_1499821169310\_t_env\lib\json\__init__.py", line 265, in load
    return loads(fp.read(),
  File "C:\bld\lektor_1499821169310\_t_env\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 713: character maps to <undefined>
```

**Comment by rlaverde** [comment]
I think It'll be enough to change this line https://github.com/lektor/lektor/blob/master/lektor/i18n.py#L16:

`with open(os.path.join(translations_path, _lang + '.json')) as f:`
to
`with open(os.path.join(translations_path, _lang + '.json'), encoding="utf8") as f:`

I could make the PR, but I don't have a Windows environment to test it.

see: https://stackoverflow.com/a/9233174/1335555

**Comment by goanpeca** [comment]
@rlaverde that could work, but not sure if it is the right fix.

**Comment by nixjdm** [comment]
That looks like it might fix the problem in Python 3, but introduce another in Python 2 if you aren't a little careful. In py2, open can't receive the encoding arg. For the Python 2 solution, we'd need to add a 

```from io import open```

to make this work still in Python 2 still: https://stackoverflow.com/questions/10971033/backporting-python-3-openencoding-utf-8-to-python-2 . The speed hit shouldn't be an issue in 2.7.

**Comment by nixjdm** [comment]
@goanpeca thanks for the appveyor link. I should look into appveyor more. I'm curious if we can have automated Windows testing on it, since Travis CI can't handle Windows yet.

**Comment by andresperezcera** [comment]
Hey, but this hasn't been solved, why is it closed? Or, how could I solve this?
