### ISSUE TITLE
Rsync deploy doesn't work on Python 3

### ISSUE THREAD

**Issue by sephii** [lektor/lektor#462]
When using the following configuration:

```
[servers.production]
target = rsync://travisci@myhost:2202/var/www/httpdocs
```

Running `lektor deploy production` raises the following exception:

```
Traceback (most recent call last):
  File "/tmp/testenv/bin/lektor", line 11, in <module>
    sys.exit(main())
  File "/tmp/testenv/lib/python3.4/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/testenv/lib/python3.4/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/tmp/testenv/lib/python3.4/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/tmp/testenv/lib/python3.4/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/testenv/lib/python3.4/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/tmp/testenv/lib/python3.4/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/tmp/testenv/lib/python3.4/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/tmp/testenv/lib/python3.4/site-packages/lektor/cli.py", line 301, in deploy_cmd
    for line in event_iter:
  File "/tmp/testenv/lib/python3.4/site-packages/lektor/publisher.py", line 231, in publish
    client = self.get_command(target_url, tempdir, credentials)
  File "/tmp/testenv/lib/python3.4/site-packages/lektor/publisher.py", line 220, in get_command
    target.append(username.encode('utf-8') + '@')
TypeError: can't concat bytes to str
```

The error only occurs on Python 3, this works fine on Python 2.7.

**Comment by davidism** [comment]
Duplicate of #424

**Comment by sephii** [comment]
Thanks for noticing!
