### ISSUE TITLE
FTP sync fails on recursion

### ISSUE THREAD

**Issue by bbbart** [lektor/lektor#465]
When deploying a site through FTP using Python 3, one gets the known str vs bytes issue (#462 and #424). When removing the encoding to utf-8 from `publisher.py`, a successful FTP connection is made and files in the root directory are uploaded successfully. However, anything in `static` for example doesn't get synchronised, and `publisher.py` bails out as well with an `AttributeError`. Here is the output of a minimal example (after having removed the utf-8 conversion of the username and password as mentioned above):

    Deploying to One
      Build cache: /home/bbbart/.cache/lektor/builds/5be014a44e706e664d77b3c8cc3df2d9
      Target: ftp://<user>@<host>
      000 Connecting to server ...
      220 Welcome to One.com FTP.
      230 OK. Current restricted directory is /
      000 Using passive mode: yes
      250 OK. Current directory is /
      000 Connected!
      000 Reading server state ...
      000 Begin sync ...
      000 Updating index.html
      a bytes-like object is required, not 'str'
      000 Updating poster@760.png
      200 TYPE is now 8-bit binary
      227 Entering Passive Mode (46,30,211,164,241,21).
      550 Sorry, but that file doesn't exist
      250 Deleted poster@760.png
      550 Sorry, but that file doesn't exist
      000 Updating poster.png
      200 TYPE is now 8-bit binary
      227 Entering Passive Mode (46,30,211,164,245,80).
      550 Sorry, but that file doesn't exist
      250 Deleted poster.png
      550 Sorry, but that file doesn't exist
      000 Updating static/style.css
      550 Can't create directory: File exists
      200 TYPE is now 8-bit binary
      550 Sorry, but that file doesn't exist
      250 Deleted static/style.css
      550 Sorry, but that file doesn't exist
      000 Updating static/scripts.js
      200 TYPE is now 8-bit binary
      227 Entering Passive Mode (46,30,211,164,242,105).
      550 Sorry, but that file doesn't exist
      250 Deleted static/scripts.js
      550 Sorry, but that file doesn't exist
      000 Sync done!
      000 Consolidating server state ...
    Traceback (most recent call last):
      File "/home/bbbart/bin/lektor", line 11, in <module>
        sys.exit(main())
      File "/home/bbbart/.local/lib/lektor/lib/python3.6/site-packages/click/core.py", line 722, in __call__
        return self.main(*args, **kwargs)
      File "/home/bbbart/.local/lib/lektor/lib/python3.6/site-packages/click/core.py", line 697, in main
        rv = self.invoke(ctx)
      File "/home/bbbart/.local/lib/lektor/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/home/bbbart/.local/lib/lektor/lib/python3.6/site-packages/click/core.py", line 895, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/home/bbbart/.local/lib/lektor/lib/python3.6/site-packages/click/core.py", line 535, in invoke
        return callback(*args, **kwargs)
      File "/home/bbbart/.local/lib/lektor/lib/python3.6/site-packages/click/decorators.py", line 64, in new_func
        return ctx.invoke(f, obj, *args[1:], **kwargs)
      File "/home/bbbart/.local/lib/lektor/lib/python3.6/site-packages/click/core.py", line 535, in invoke
        return callback(*args, **kwargs)
      File "/home/bbbart/.local/lib/lektor/lib/python3.6/site-packages/lektor/cli.py", line 301, in deploy_cmd
        for line in event_iter:
      File "/home/bbbart/.local/lib/lektor/lib/python3.6/site-packages/lektor/publisher.py", line 524, in publish
        for event in con.drain_log():
      File "/home/bbbart/.local/lib/lektor/lib/python3.6/site-packages/lektor/publisher.py", line 256, in drain_log
        for line in chunk.splitlines():
    AttributeError: 'error_reply' object has no attribute 'splitlines'

The result is that everything in `/static` is removed, but not reuploaded.

**Comment by xlotlu** [comment]
@bbbart could you please test if this is still the case? #424 has been fixed for a long time now.

**Comment by yagebu** [comment]
Closing this stale issue
