### ISSUE TITLE
ImportError: cannot import name _remove_dead_weakref

### ISSUE THREAD

**Issue by animeshkrishnabulusu** [lektor/lektor#472]
Hello.

I get the following error when I run the `lektor server`. I noticed this after my today package update.

```
animesh@garuda:~/projects/lektorproject$ lektor server
Traceback (most recent call last):
  File "/home/animesh/.npm-global/bin/lektor", line 7, in <module>
    from lektor.cli import main
  File "/home/animesh/.local/lib/lektor/local/lib/python2.7/site-packages/lektor/cli.py", line 5, in <module>
    import click
  File "/home/animesh/.local/lib/lektor/local/lib/python2.7/site-packages/click/__init__.py", line 18, in <module>
    from .core import Context, BaseCommand, Command, MultiCommand, Group, \
  File "/home/animesh/.local/lib/lektor/local/lib/python2.7/site-packages/click/core.py", line 8, in <module>
    from .types import convert_type, IntRange, BOOL
  File "/home/animesh/.local/lib/lektor/local/lib/python2.7/site-packages/click/types.py", line 4, in <module>
    from ._compat import open_stream, text_type, filename_to_ui, \
  File "/home/animesh/.local/lib/lektor/local/lib/python2.7/site-packages/click/_compat.py", line 6, in <module>
    from weakref import WeakKeyDictionary
  File "/usr/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref

```

I am on Debian Buster. Lektor 3.0.1 was installed using the curl script on the downloads page.

Output of `uname -a`

`Linux garuda 4.13.0-1-amd64 #1 SMP Debian 4.13.4-2 (2017-10-15) x86_64 GNU/Linux`

Help!

**Comment by animeshkrishnabulusu** [comment]
This happens for any lektor command including just `lektor`

**Comment by animeshkrishnabulusu** [comment]
I reinstalled lektor using the curl one-liner and am able to run the commands again.
