### ISSUE TITLE
lektor plugins add explodes on python3

### ISSUE THREAD

**Issue by dwt** [lektor/lektor#482]
```sh
(venv:homepage-RG7arHcO) dwt@crest ~/Code/Projekte/homepage % lektor plugins add creative-commons
Traceback (most recent call last):
  File "/Users/dwt/.virtualenvs/homepage-RG7arHcO/bin/lektor", line 11, in <module>
    sys.exit(main())
  File "/Users/dwt/.virtualenvs/homepage-RG7arHcO/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/dwt/.virtualenvs/homepage-RG7arHcO/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/dwt/.virtualenvs/homepage-RG7arHcO/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/dwt/.virtualenvs/homepage-RG7arHcO/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/dwt/.virtualenvs/homepage-RG7arHcO/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/dwt/.virtualenvs/homepage-RG7arHcO/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/dwt/.virtualenvs/homepage-RG7arHcO/lib/python3.6/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/Users/dwt/.virtualenvs/homepage-RG7arHcO/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/dwt/.virtualenvs/homepage-RG7arHcO/lib/python3.6/site-packages/lektor/cli.py", line 462, in plugins_add_cmd
    info = add_package_to_project(project, name)
  File "/Users/dwt/.virtualenvs/homepage-RG7arHcO/lib/python3.6/site-packages/lektor/packages.py", line 61, in add_package_to_project
    cfg['packages.%s' % canonical_name] = version
  File "/Users/dwt/.virtualenvs/homepage-RG7arHcO/lib/python3.6/site-packages/inifile.py", line 463, in __setitem__
    self._changes[name] = self.dialect.to_string(value)
  File "/Users/dwt/.virtualenvs/homepage-RG7arHcO/lib/python3.6/site-packages/inifile.py", line 172, in to_string
    if isinstance(value, (int, long, float)):
NameError: name 'long' is not defined

``` 

This just happened - it seems lektor should be using `six` or `futurize` to deal with py2/3 differences.

**Comment by davidism** [comment]
That error's in inifile, a separate package: https://github.com/mitsuhiko/python-inifile

**Comment by dwt** [comment]
Closing, as this is an upstream package.

**Comment by nixjdm** [comment]
FYI, this should now work. @mitsuhiko just pushed an updated version of https://github.com/mitsuhiko/python-inifile.
