### ISSUE TITLE
ValueError: unknown locale: UTF-8 on Lektor, version 3.1

### ISSUE THREAD

**Issue by sgrinschpun** [lektor/lektor#495]
After upgrading to version 3.1 I get the error

`ValueError: unknown locale: UTF-8`

when doing lektor server or lektor build on a project created with lektor 3.0

**Comment by davidism** [comment]
What's the full traceback? What version of Python are you using? What is your computer's configured locale? Do you get this error with a new project, or just a 3.0-created project?

**Comment by sgrinschpun** [comment]
1. Full Traceback for lektor server

 * Project path: /Users/sgrinschpun/code/susy2018/susy2018.lektorproject
 * Output path: /Users/sgrinschpun/Library/Caches/Lektor/builds/dad469a9825440bbfde72e104aef32e0
Traceback (most recent call last):
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/lektor/devserver.py", line 44, in build
    extra_flags=self.extra_flags)
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/lektor/builder.py", line 970, in __init__
    con = self.connect_to_database()
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/lektor/builder.py", line 1002, in connect_to_database
    system_encoding = locale.getdefaultlocale()[1]
  File "/usr/local/lib/lektor/lib/python2.7/locale.py", line 543, in getdefaultlocale
Traceback (most recent call last):
  File "/usr/local/bin/lektor", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/lektor/cli.py", line 371, in server_cmd
    browse=browse)
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/lektor/devserver.py", line 134, in run_server
    return _parse_localename(localename)
    and SilentWSGIRequestHandler or WSGIRequestHandler)
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/werkzeug/serving.py", line 814, in run_simple
      File "/usr/local/lib/lektor/lib/python2.7/locale.py", line 475, in _parse_localename
inner()
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/werkzeug/serving.py", line 774, in inner
    fd=fd)
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/werkzeug/serving.py", line 660, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/werkzeug/serving.py", line 577, in __init__
    self.address_family), handler)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 420, in __init__
    self.server_bind()
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 434, in server_bind
    self.socket.bind(self.server_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 48] Address already in use
IFAE-Comm-MacBook-Pro-3:susy2018 sgrinschpun$ lektor server
 * Project path: /Users/sgrinschpun/code/susy2018/susy2018.lektorproject
 * Output path: /Users/sgrinschpun/Library/Caches/Lektor/builds/dad469a9825440bbfde72e104aef32e0
Traceback (most recent call last):
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/lektor/devserver.py", line 44, in build
    extra_flags=self.extra_flags)
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/lektor/builder.py", line 970, in __init__
    con = self.connect_to_database()
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/lektor/builder.py", line 1002, in connect_to_database
    system_encoding = locale.getdefaultlocale()[1]
  File "/usr/local/lib/lektor/lib/python2.7/locale.py", line 543, in getdefaultlocale
    return _parse_localename(localename)
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
  File "/usr/local/lib/lektor/lib/python2.7/locale.py", line 475, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8'

2. Python version: 2.7.10

3. Computer's locale:
LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=

4. Same error on projects created with Lektor 3.1

**Comment by davidism** [comment]
Can you format your traceback using code blocks? It's easier to read that way.

That first traceback seems unrelated, it's just saying you're already running something bound to that port already (probably another instance of the Lektor server).

**Comment by sgrinschpun** [comment]
Sorry about this. Let's see if this helps:

`Project path: /Users/sgrinschpun/code/susy2018/susy2018.lektorproject`
`Output path: /Users/sgrinschpun/Library/Caches/Lektor/builds/dad469a9825440bbfde72e104aef32e0`
`Traceback (most recent call last):
File "/usr/local/lib/lektor/lib/python2.7/site-packages/lektor/devserver.py", line 44, in build
extra_flags=self.extra_flags)
File "/usr/local/lib/lektor/lib/python2.7/site-packages/lektor/builder.py", line 970, in init
con = self.connect_to_database()
File "/usr/local/lib/lektor/lib/python2.7/site-packages/lektor/builder.py", line 1002, in connect_to_database
system_encoding = locale.getdefaultlocale()[1]
File "/usr/local/lib/lektor/lib/python2.7/locale.py", line 543, in getdefaultlocale`
`return _parse_localename(localename)`
`Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)`
`File "/usr/local/lib/lektor/lib/python2.7/locale.py", line 475, in _parse_localename`
`raise ValueError, 'unknown locale: %s' % localename`
`ValueError: unknown locale: UTF-8`

**Comment by sgrinschpun** [comment]
Hi

As per https://coderwall.com/p/-k_93g/mac-os-x-valueerror-unknown-locale-utf-8-in-python
this seems to be a generla python + OSX problem
I followed the instructions and now it is working

sorry for the trouble

**Comment by nixjdm** [comment]
Looks like you've got it figured out @IFAE, so I'll close this issue. Thanks
