### ISSUE TITLE
UnboundLocalError: local variable 'pieces' referenced before assignment

### ISSUE THREAD

**Issue by toxinu** [lektor/lektor#5]
Hi there,

I just get this Traceback while testing Lektor.

``` python
Traceback (most recent call last):
  File "[HOME]/.local/lib/lektor/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "[HOME]/.local/lib/lektor/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "[HOME]/.local/lib/lektor/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "[HOME]/.local/lib/lektor/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "[HOME]/.local/lib/lektor/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "[HOME]/.local/lib/lektor/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "[HOME]/.local/lib/lektor/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "[HOME]/.local/lib/lektor/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "[HOME]/.local/lib/lektor/lib/python2.7/site-packages/lektor/admin/modules/serve.py", line 129, in serve_artifact
    artifact_name, filename = li.resolve_artifact('/' + path, pad)
  File "[HOME]/.local/lib/lektor/lib/python2.7/site-packages/lektor/admin/webui.py", line 47, in resolve_artifact
    source = pad.resolve_url_path(path)
  File "[HOME]/.local/lib/lektor/lib/python2.7/site-packages/lektor/db.py", line 1208, in resolve_url_path
    return self.asset_root.resolve_url_path(pieces)
UnboundLocalError: local variable 'pieces' referenced before assignment
```

OS: `Ubuntu 15.10`

I can investigate with pleasure it if you don't want to catch it right now.

Thank you @mitsuhiko :smile:

**Comment by mitsuhiko** [comment]
I think this might happen for misconfigured alternatives. Need to see what the right behavior is.
