### ISSUE TITLE
UnicodeEncodeError visiting page with non-ascii UTF-8 character

### ISSUE THREAD

**Issue by RotationMatrix** [lektor/lektor#683]
On my local development server, I'm receiving the following error when I visit a page with a non-ascii UTF-8 character.

```
Traceback (most recent call last):
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/lektor/admin/modules/serve.py", line 151, in serve_artifact
    return serve_up_artifact(path)
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/lektor/admin/modules/serve.py", line 130, in serve_up_artifact
    artifact_name, filename = li.resolve_artifact('/' + path, pad)
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/lektor/admin/webui.py", line 62, in resolve_artifact
    prog, _ = builder.build(source)
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/lektor/builder.py", line 1110, in build
    source=source, prog=prog)
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/lektor/pluginsystem.py", line 161, in emit
    rv[plugin.id] = handler(**kwargs)
  File "/Users/user/src/Tor DocsHackathon/manual/lego/packages/i18n/lektor_i18n.py", line 357, in on_before_build
    translator))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u201c' in position 86: ordinal not in range(128)
```

## Steps to reproduce
1. Clone https://github.com/torproject/manual
2. `$ cd manual`
3. `$ lektor server`
4. Visit http://127.0.0.1:5000/updating/

## Lektor and Python version info
```
$ lektor --version
Lektor, version 3.1.3
$ python --version
Python 2.7.16
```
OS is macOS 10.12.6.

Thanks in advance for any help! I really appreciate it!

**Comment by emmapeel2** [comment]
maybe this is a ticket for https://github.com/numericube/lektor-i18n-plugin ?

**Comment by RotationMatrix** [comment]
Yeah I was just thinking that myself. The stack trace is pointing that way.
