### ISSUE TITLE
Lektor doesn't work on MacOs 10.15.3

### ISSUE THREAD

**Issue by leonid-dubov** [lektor/lektor#740]
Looks like Lektor complety broken on latest MacOs

When I try to run `lektor server`

```
dubov@Mac-mini-Leonid bin % ./lektor --project /Volumes/My\ Book/Documents/Code/leonid.dubov.name/lektor_prj server
 * Project path: /Volumes/My Book/Documents/Code/leonid.dubov.name/lektor_prj/leonid.dubov.name.lektorproject
 * Output path: /Users/dubov/Library/Caches/Lektor/builds/3df288b4625c2b2b421e4daaf7aa6489
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
Traceback (most recent call last):
  File "/Users/dubov/Library/Python/2.7/lib/python/site-packages/lektor/devserver.py", line 44, in build
    extra_flags=self.extra_flags)
  File "/Users/dubov/Library/Python/2.7/lib/python/site-packages/lektor/builder.py", line 980, in __init__
    con = self.connect_to_database()
  File "/Users/dubov/Library/Python/2.7/lib/python/site-packages/lektor/builder.py", line 1015, in connect_to_database
    cur.execute('pragma journal_mode=WAL')
  File "/Users/dubov/Library/Python/2.7/lib/python/site-packages/lektor/builder.py", line 1013, in <lambda>
    con.text_factory = lambda x: x.decode(system_encoding, 'ignore')
TypeError: decode() argument 1 must be string, not None
```

If I try to reinstall
```
This script will install Lektor on your computer.

   Lektor seems to be installed already.
   Continuing will delete:
   /usr/local/lib/lektor
   and remove this symlink:
   /usr/local/bin/lektor

Continue? [Yn] y

Installing at:
  bin: /usr/local/bin
  app: /usr/local/lib/lektor

Continue? [Yn] y
/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file './src/virtualenv.py': [Errno 2] No such file or directory
/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file './virtualenv.py': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "<stdin>", line 151, in <module>
  File "<stdin>", line 146, in main
  File "<stdin>", line 110, in install
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by runfalk** [comment]
This seems to be locale related, apparently `locale.getdefaultlocale` will return null if the locale can't be determined. Are you using a non-standard shell by any chance?

Could you run and paste the output of `env`? (Redact anything that looks too personal)

You could also try to run lektor using `LANG=en_US.UTF-8 lektor --project /Volumes/My\ Book/Documents/Code/leonid.dubov.name/lektor_prj server`

The way you invoke lektor looks a bit odd. Normally you don't have to `cd` into the bin directory.

**Comment by roberto-arista** [comment]
Hey there,
I report the same issue on another machine, locale settings were fixed on ~/.zshrc before tryng to install with 
```
curl -sf https://www.getlektor.com/install.sh | sh
```

here's the error log
```
Welcome to Lektor

This script will install Lektor on your computer.

Installing at:
  bin: /usr/local/bin
  app: /usr/local/lib/lektor

Continue? [Yn] y
/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file './src/virtualenv.py': [Errno 2] No such file or directory
/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file './virtualenv.py': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "<stdin>", line 151, in <module>
  File "<stdin>", line 146, in main
  File "<stdin>", line 110, in install
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in _init_
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

any idea?

**Comment by runfalk** [comment]
Looking at this some more it seems to be directly related to #720.
