### ISSUE TITLE
def computed_height() can fail, if dimensions are None

### ISSUE THREAD

**Issue by telmich** [lektor/lektor#752]
I patched the function to debug as follows:

```
def computed_height(source_image, width, actual_width, actual_height):
    # If the file is a JPEG file and the EXIF header shows that the image
    # is rotated, imagemagick will auto-orient the file. That is, a 400x200
    # file where the target width is 100px will *not* be converted to a
    # 100x50 image, but to 100x200.

    print("image = {} {} {} {}".format(source_image, width, actual_width, actual_height))
    import sys
    sys.exit(3)
```

We see the following output:

```
Started build
U u/blog/page/2/index.html
image = /home/nico/vcs/ungleich-staticcms/content/u/blog/video-conference-for-all/jitsi-bg.jpg 240 None None
E u/blog/page/2/index.html (SystemExit: 3)
U u/blog/page/3/index.html
image = /home/nico/vcs/ungleich-staticcms/content/u/blog/zerocarbon-digital/zerocarbon-meditation.jpg 240 4000 2247
E u/blog/page/3/index.html (SystemExit: 3)
U u/blog/page/4/index.html
image = /home/nico/vcs/ungleich-staticcms/content/u/blog/phasing-out-of-ubuntu-1404/ubuntu-14.04.2-trusty-tahr-cr.jpg 240 419 419
```

So it is possible that the values for actual_width, actual_height can be None.

The image in question is this one:

```
(venv) [21:16] line:video-conference-for-all% file jitsi-bg.jpg 
jitsi-bg.jpg: JPEG image data, baseline, precision 8, 1080x469, components 3
```
I have attached the image in question for further debugging, however 
![jitsi-bg](https://user-images.githubusercontent.com/9397/79497348-cd9e3980-8027-11ea-9181-8f8c5ca42a61.jpg)

The original traceback in the lektor code is:

```
Traceback (most recent call last):
  File "/home/nico/vcs/ungleich-staticcms/venv/lib/python3.7/site-packages/lektor/builder.py", line 800, in update
    yield ctx
  File "/home/nico/vcs/ungleich-staticcms/venv/lib/python3.7/site-packages/lektor/builder.py", line 1070, in build_artifact
    build_func(artifact)
  File "/home/nico/vcs/ungleich-staticcms/venv/lib/python3.7/site-packages/lektor/build_programs.py", line 184, in build_artifact
    self.source['_template'], this=self.source)
  File "/home/nico/vcs/ungleich-staticcms/venv/lib/python3.7/site-packages/lektor/builder.py", line 655, in render_template_into
    this=this, **extra)
  File "/home/nico/vcs/ungleich-staticcms/venv/lib/python3.7/site-packages/lektor/environment.py", line 542, in render_template
    return self.jinja_env.get_or_select_template(name).render(ctx)
  File "/home/nico/vcs/ungleich-staticcms/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/nico/vcs/ungleich-staticcms/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/nico/vcs/ungleich-staticcms/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/nico/vcs/ungleich-staticcms/templates/blog.html", line 3, in top-level template code
    {% from "macros/pagination.html" import render_pagination %}
  File "/home/nico/vcs/ungleich-staticcms/templates/layout.html", line 79, in top-level template code
    {% block body %}{% endblock %}
  File "/home/nico/vcs/ungleich-staticcms/templates/blog.html", line 25, in block "body"
    {{ render_blog_post(child, from_index=true) }}
  File "/home/nico/vcs/ungleich-staticcms/venv/lib/python3.7/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "/home/nico/vcs/ungleich-staticcms/templates/macros/blog.html", line 7, in template
    <h2><a href="{{ post|url }}">{% if image %}<img src="{{ image.thumbnail(240)|url }}" alt=""/>{% else %}<div class="blog-post-placeholder"></div>{% endif %}</a></h2>
  File "/home/nico/vcs/ungleich-staticcms/venv/lib/python3.7/site-packages/lektor/db.py", line 790, in thumbnail
    width=width, height=height, crop=crop, quality=quality)
  File "/home/nico/vcs/ungleich-staticcms/venv/lib/python3.7/site-packages/lektor/imagetools.py", line 471, in make_thumbnail
    source_height)
  File "/home/nico/vcs/ungleich-staticcms/venv/lib/python3.7/site-packages/lektor/imagetools.py", line 418, in computed_height
    return int(float(actual_height) * (float(width) / float(actual_width)))
TypeError: float() argument must be a string or a number, not 'NoneType'
```

So I suspect that one of the callers is unable to correctly determine the image size, so probably 2 fixes are required:

- find the source where the none values are produce
- make def computed_height() more robust to none values

ping @fnux @verysanghee

**Comment by xlotlu** [comment]
@telmich that function doesn't exist for a long time now. (That nobody did a release since then... oh well.)

Please use master, there were a few jpeg handling bugs fixed:

```pycon
In [1]: from lektor.imagetools import get_image_info                                    

In [2]: get_image_info(open('/tmp/79497348-cd9e3980-8027-11ea-9181-8f8c5ca42a61.jpg', 'rb'))   
Out[2]: ('jpeg', 1080, 469)
```

**Comment by telmich** [comment]
@xlotlu is there and chance that you create a new release containing this? We use a lot of automated build systems depending on pypi at the moment, so installing from git/master is a bit tricky

**Comment by xlotlu** [comment]
> @xlotlu is there and chance that you create a new release containing this? We use a lot of automated build systems depending on pypi at the moment, so installing from git/master is a bit tricky

@telmich not my call, I'm just a dev.

@lektor/developers ping.

**Comment by runfalk** [comment]
@telmich for now you can do `pip install git+https://github.com/lektor/lektor/` as a workaround.

**Comment by telmich** [comment]
It seems I've the exact same problem again, with a different picture:

```
  File "/home/nico/vcs/ungleich-staticcms/templates/macros/blog.html", line 7, in template
    <h2><a href="{{ post|url }}">{% if image %}<img src="{{ image.thumbnail(240)|url }}" alt=""/>{% else %}<div class="blog-post-placeholder"></div>{% endif %}</a></h2>
  File "/home/nico/vcs/ungleich-staticcms/venv/lib/python3.7/site-packages/lektor/db.py", line 790, in thumbnail
    width=width, height=height, crop=crop, quality=quality)
  File "/home/nico/vcs/ungleich-staticcms/venv/lib/python3.7/site-packages/lektor/imagetools.py", line 471, in make_thumbnail
    source_height)
  File "/home/nico/vcs/ungleich-staticcms/venv/lib/python3.7/site-packages/lektor/imagetools.py", line 418, in computed_height
    return int(float(actual_height) * (float(width) / float(actual_width)))
TypeError: float() argument must be a string or a number, not 'NoneType'
```

Just installed lektor via pip install as described above. Attached is the picture.

![penguin-bg](https://user-images.githubusercontent.com/9397/84202122-79a05600-aaa8-11ea-9850-224f101137ab.jpg)

**Comment by telmich** [comment]
@xlotlu I might be mistaken, but I ran above `pip install git+https://github.com/lektor/lektor/` which, afaik, should pull from master. Or am I wrong?

**Comment by runfalk** [comment]
It should indeed pull from master. However, if you look at line 418 of imagetools.py (https://github.com/lektor/lektor/blob/master/lektor/imagetools.py#L418) you can see that it doesn't match the traceback you posted.

Maybe you didn't uninstall Lektor before trying to install latest master? If lektor was already install it will not try to upgrade unless you force it to. The easiest way to know for sure is to recreate the virtualenv. Note that the admin interface will be broken since the JavaScript is not compiled when installing it this way.

**Comment by telmich** [comment]
OMG. I've now spend an hour to discover something "funny": even in the venv, lektor from the system installation (!) was in the PATH before the venv lektor. I assumed that venv would always prepend the PATH, but that seems to have been a wrong assumption.

Thanks a lot for insisting on me using the wrong version!

**Comment by runfalk** [comment]
Glad to hear it worked out for you! Hopefully this will soon be a non-issue. New release is in the works.
