### ISSUE TITLE
virtualenv.py is missing in install.sh

### ISSUE THREAD

**Issue by sporksmith** [lektor/lektor#763]
Attempting to follow instructions from the web site, on Ubuntu 18.04:
```
$ curl -sf https://www.getlektor.com/install.sh | sh

Welcome to Lektor

This script will install Lektor on your computer.

Installing at:
  bin: /home/jnewsome/.local/bin
  app: /home/jnewsome/.local/lib/lektor

Continue? [Yn] 
/usr/bin/python: can't open file './src/virtualenv.py': [Errno 2] No such file or directory
/usr/bin/python: can't open file './virtualenv.py': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "<stdin>", line 151, in <module>
  File "<stdin>", line 146, in main
  File "<stdin>", line 110, in install
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by sporksmith** [comment]
It seems to be looking for `virtualenv.py` in a virtualenv tarball that it downloaded and extracted. Here are the contents of that tarball:
```
/tmp/tmpfh7gtult/
/tmp/tmpfh7gtult/.readthedocs.yml
/tmp/tmpfh7gtult/PKG-INFO
/tmp/tmpfh7gtult/pyproject.toml
/tmp/tmpfh7gtult/tasks
/tmp/tmpfh7gtult/tasks/update_embedded.py
/tmp/tmpfh7gtult/tasks/__main__zipapp.py
/tmp/tmpfh7gtult/tasks/make_zipapp.py
/tmp/tmpfh7gtult/setup.py
/tmp/tmpfh7gtult/.pre-commit-config.yaml
/tmp/tmpfh7gtult/docs
/tmp/tmpfh7gtult/docs/development.rst
/tmp/tmpfh7gtult/docs/extend.rst
/tmp/tmpfh7gtult/docs/installation.rst
/tmp/tmpfh7gtult/docs/cli_interface.rst
/tmp/tmpfh7gtult/docs/changelog.rst
/tmp/tmpfh7gtult/docs/_static
/tmp/tmpfh7gtult/docs/_static/custom.css
/tmp/tmpfh7gtult/docs/conf.py
/tmp/tmpfh7gtult/docs/user_guide.rst
/tmp/tmpfh7gtult/docs/render_cli.py
/tmp/tmpfh7gtult/docs/changelog
/tmp/tmpfh7gtult/docs/changelog/examples.rst
/tmp/tmpfh7gtult/docs/changelog/template.jinja2
/tmp/tmpfh7gtult/docs/index.rst
/tmp/tmpfh7gtult/.github
/tmp/tmpfh7gtult/.github/ISSUE_TEMPLATE
/tmp/tmpfh7gtult/.github/ISSUE_TEMPLATE/bug-report.md
/tmp/tmpfh7gtult/.github/ISSUE_TEMPLATE/config.yml
/tmp/tmpfh7gtult/.github/ISSUE_TEMPLATE/bug_report.md
/tmp/tmpfh7gtult/.github/ISSUE_TEMPLATE/feature-request.md
/tmp/tmpfh7gtult/tests
/tmp/tmpfh7gtult/tests/integration
/tmp/tmpfh7gtult/tests/integration/test_zipapp.py
/tmp/tmpfh7gtult/tests/conftest.py
/tmp/tmpfh7gtult/tests/unit
/tmp/tmpfh7gtult/tests/unit/discovery
/tmp/tmpfh7gtult/tests/unit/discovery/py_info
/tmp/tmpfh7gtult/tests/unit/discovery/py_info/test_py_info_exe_based_of.py
/tmp/tmpfh7gtult/tests/unit/discovery/py_info/test_py_info.py
/tmp/tmpfh7gtult/tests/unit/discovery/windows
/tmp/tmpfh7gtult/tests/unit/discovery/windows/test_windows_pep514.py
/tmp/tmpfh7gtult/tests/unit/discovery/windows/winreg-mock-values.py
/tmp/tmpfh7gtult/tests/unit/discovery/test_discovery.py
/tmp/tmpfh7gtult/tests/unit/discovery/test_py_spec.py
/tmp/tmpfh7gtult/tests/unit/create
/tmp/tmpfh7gtult/tests/unit/create/conftest.py
/tmp/tmpfh7gtult/tests/unit/create/virtualenv-16.7.9-py2.py3-none-any.whl
/tmp/tmpfh7gtult/tests/unit/create/console_app
/tmp/tmpfh7gtult/tests/unit/create/console_app/setup.py
/tmp/tmpfh7gtult/tests/unit/create/console_app/demo
/tmp/tmpfh7gtult/tests/unit/create/console_app/demo/__main__.py
/tmp/tmpfh7gtult/tests/unit/create/console_app/demo/__init__.py
/tmp/tmpfh7gtult/tests/unit/create/console_app/setup.cfg
/tmp/tmpfh7gtult/tests/unit/create/test_creator.py
/tmp/tmpfh7gtult/tests/unit/create/test_interpreters.py
/tmp/tmpfh7gtult/tests/unit/config
/tmp/tmpfh7gtult/tests/unit/config/test___main__.py
/tmp/tmpfh7gtult/tests/unit/config/cli
/tmp/tmpfh7gtult/tests/unit/config/cli/test_parser.py
/tmp/tmpfh7gtult/tests/unit/config/test_env_var.py
/tmp/tmpfh7gtult/tests/unit/test_run.py
/tmp/tmpfh7gtult/tests/unit/activation
/tmp/tmpfh7gtult/tests/unit/activation/test_python_activator.py
/tmp/tmpfh7gtult/tests/unit/activation/test_xonsh.py
/tmp/tmpfh7gtult/tests/unit/activation/test_fish.py
/tmp/tmpfh7gtult/tests/unit/activation/conftest.py
/tmp/tmpfh7gtult/tests/unit/activation/test_bash.py
/tmp/tmpfh7gtult/tests/unit/activation/test_batch.py
/tmp/tmpfh7gtult/tests/unit/activation/test_powershell.py
/tmp/tmpfh7gtult/tests/unit/activation/test_activation_support.py
/tmp/tmpfh7gtult/tests/unit/activation/test_csh.py
/tmp/tmpfh7gtult/tests/unit/test_util.py
/tmp/tmpfh7gtult/tests/unit/seed
/tmp/tmpfh7gtult/tests/unit/seed/test_boostrap_link_via_app_data.py
/tmp/tmpfh7gtult/tests/unit/seed/embed
/tmp/tmpfh7gtult/tests/unit/seed/embed/wheels
/tmp/tmpfh7gtult/tests/unit/seed/embed/wheels/test_acquire.py
/tmp/tmpfh7gtult/tests/unit/seed/test_pip_invoke.py
/tmp/tmpfh7gtult/tests/unit/seed/greet
/tmp/tmpfh7gtult/tests/unit/seed/greet/greet3.c
/tmp/tmpfh7gtult/tests/unit/seed/greet/setup.py
/tmp/tmpfh7gtult/tests/unit/seed/greet/greet2.c
/tmp/tmpfh7gtult/tests/unit/seed/test_extra_install.py
/tmp/tmpfh7gtult/src
/tmp/tmpfh7gtult/src/virtualenv
/tmp/tmpfh7gtult/src/virtualenv/pyenv_cfg.py
/tmp/tmpfh7gtult/src/virtualenv/version.py
/tmp/tmpfh7gtult/src/virtualenv/info.py
/tmp/tmpfh7gtult/src/virtualenv/run
/tmp/tmpfh7gtult/src/virtualenv/run/plugin
/tmp/tmpfh7gtult/src/virtualenv/run/plugin/creators.py
/tmp/tmpfh7gtult/src/virtualenv/run/plugin/base.py
/tmp/tmpfh7gtult/src/virtualenv/run/plugin/discovery.py
/tmp/tmpfh7gtult/src/virtualenv/run/plugin/seeders.py
/tmp/tmpfh7gtult/src/virtualenv/run/plugin/__init__.py
/tmp/tmpfh7gtult/src/virtualenv/run/plugin/activators.py
/tmp/tmpfh7gtult/src/virtualenv/run/app_data.py
/tmp/tmpfh7gtult/src/virtualenv/run/__init__.py
/tmp/tmpfh7gtult/src/virtualenv/discovery
/tmp/tmpfh7gtult/src/virtualenv/discovery/windows
/tmp/tmpfh7gtult/src/virtualenv/discovery/windows/pep514.py
/tmp/tmpfh7gtult/src/virtualenv/discovery/windows/__init__.py
/tmp/tmpfh7gtult/src/virtualenv/discovery/py_spec.py
/tmp/tmpfh7gtult/src/virtualenv/discovery/py_info.py
/tmp/tmpfh7gtult/src/virtualenv/discovery/discover.py
/tmp/tmpfh7gtult/src/virtualenv/discovery/cached_py_info.py
/tmp/tmpfh7gtult/src/virtualenv/discovery/builtin.py
/tmp/tmpfh7gtult/src/virtualenv/discovery/__init__.py
/tmp/tmpfh7gtult/src/virtualenv/create
/tmp/tmpfh7gtult/src/virtualenv/create/creator.py
/tmp/tmpfh7gtult/src/virtualenv/create/describe.py
/tmp/tmpfh7gtult/src/virtualenv/create/debug.py
/tmp/tmpfh7gtult/src/virtualenv/create/__init__.py
/tmp/tmpfh7gtult/src/virtualenv/create/via_global_ref
/tmp/tmpfh7gtult/src/virtualenv/create/via_global_ref/venv.py
/tmp/tmpfh7gtult/src/virtualenv/create/via_global_ref/api.py
/tmp/tmpfh7gtult/src/virtualenv/create/via_global_ref/__init__.py
/tmp/tmpfh7gtult/src/virtualenv/create/via_global_ref/builtin
/tmp/tmpfh7gtult/src/virtualenv/create/via_global_ref/builtin/pypy
/tmp/tmpfh7gtult/src/virtualenv/create/via_global_ref/builtin/pypy/pypy3.py
/tmp/tmpfh7gtult/src/virtualenv/create/via_global_ref/builtin/pypy/pypy2.py
/tmp/tmpfh7gtult/src/virtualenv/create/via_global_ref/builtin/pypy/common.py
/tmp/tmpfh7gtult/src/virtualenv/create/via_global_ref/builtin/pypy/__init__.py
/tmp/tmpfh7gtult/src/virtualenv/create/via_global_ref/builtin/via_global_self_do.py
/tmp/tmpfh7gtult/src/virtualenv/create/via_global_ref/builtin/cpython
/tmp/tmpfh7gtult/src/virtualenv/create/via_global_ref/builtin/cpython/cpython3.py
/tmp/tmpfh7gtult/src/virtualenv/create/via_global_ref/builtin/cpython/cpython2.py
/tmp/tmpfh7gtult/src/virtualenv/create/via_global_ref/builtin/cpython/common.py
/tmp/tmpfh7gtult/src/virtualenv/create/via_global_ref/builtin/cpython/__init__.py
/tmp/tmpfh7gtult/src/virtualenv/create/via_global_ref/builtin/cpython/mac_os.py
/tmp/tmpfh7gtult/src/virtualenv/create/via_global_ref/builtin/ref.py
/tmp/tmpfh7gtult/src/virtualenv/create/via_global_ref/builtin/builtin_way.py
/tmp/tmpfh7gtult/src/virtualenv/create/via_global_ref/builtin/python2
/tmp/tmpfh7gtult/src/virtualenv/create/via_global_ref/builtin/python2/site.py
/tmp/tmpfh7gtult/src/virtualenv/create/via_global_ref/builtin/python2/__init__.py
/tmp/tmpfh7gtult/src/virtualenv/create/via_global_ref/builtin/python2/python2.py
/tmp/tmpfh7gtult/src/virtualenv/create/via_global_ref/builtin/__init__.py
/tmp/tmpfh7gtult/src/virtualenv/create/via_global_ref/store.py
/tmp/tmpfh7gtult/src/virtualenv/create/via_global_ref/_virtualenv.py
/tmp/tmpfh7gtult/src/virtualenv/session.py
/tmp/tmpfh7gtult/src/virtualenv/config
/tmp/tmpfh7gtult/src/virtualenv/config/convert.py
/tmp/tmpfh7gtult/src/virtualenv/config/cli
/tmp/tmpfh7gtult/src/virtualenv/config/cli/parser.py
/tmp/tmpfh7gtult/src/virtualenv/config/cli/__init__.py
/tmp/tmpfh7gtult/src/virtualenv/config/env_var.py
/tmp/tmpfh7gtult/src/virtualenv/config/ini.py
/tmp/tmpfh7gtult/src/virtualenv/config/__init__.py
/tmp/tmpfh7gtult/src/virtualenv/report.py
/tmp/tmpfh7gtult/src/virtualenv/error.py
/tmp/tmpfh7gtult/src/virtualenv/__main__.py
/tmp/tmpfh7gtult/src/virtualenv/activation
/tmp/tmpfh7gtult/src/virtualenv/activation/fish
/tmp/tmpfh7gtult/src/virtualenv/activation/fish/activate.fish
/tmp/tmpfh7gtult/src/virtualenv/activation/fish/__init__.py
/tmp/tmpfh7gtult/src/virtualenv/activation/bash
/tmp/tmpfh7gtult/src/virtualenv/activation/bash/activate.sh
/tmp/tmpfh7gtult/src/virtualenv/activation/bash/__init__.py
/tmp/tmpfh7gtult/src/virtualenv/activation/batch
/tmp/tmpfh7gtult/src/virtualenv/activation/batch/activate.bat
/tmp/tmpfh7gtult/src/virtualenv/activation/batch/deactivate.bat
/tmp/tmpfh7gtult/src/virtualenv/activation/batch/__init__.py
/tmp/tmpfh7gtult/src/virtualenv/activation/batch/pydoc.bat
/tmp/tmpfh7gtult/src/virtualenv/activation/via_template.py
/tmp/tmpfh7gtult/src/virtualenv/activation/__init__.py
/tmp/tmpfh7gtult/src/virtualenv/activation/activator.py
/tmp/tmpfh7gtult/src/virtualenv/activation/python
/tmp/tmpfh7gtult/src/virtualenv/activation/python/activate_this.py
/tmp/tmpfh7gtult/src/virtualenv/activation/python/__init__.py
/tmp/tmpfh7gtult/src/virtualenv/activation/powershell
/tmp/tmpfh7gtult/src/virtualenv/activation/powershell/activate.ps1
/tmp/tmpfh7gtult/src/virtualenv/activation/powershell/__init__.py
/tmp/tmpfh7gtult/src/virtualenv/activation/cshell
/tmp/tmpfh7gtult/src/virtualenv/activation/cshell/activate.csh
/tmp/tmpfh7gtult/src/virtualenv/activation/cshell/__init__.py
/tmp/tmpfh7gtult/src/virtualenv/activation/xonsh
/tmp/tmpfh7gtult/src/virtualenv/activation/xonsh/__init__.py
/tmp/tmpfh7gtult/src/virtualenv/activation/xonsh/activate.xsh
/tmp/tmpfh7gtult/src/virtualenv/util
/tmp/tmpfh7gtult/src/virtualenv/util/six.py
/tmp/tmpfh7gtult/src/virtualenv/util/lock.py
/tmp/tmpfh7gtult/src/virtualenv/util/path
/tmp/tmpfh7gtult/src/virtualenv/util/path/_sync.py
/tmp/tmpfh7gtult/src/virtualenv/util/path/_pathlib
/tmp/tmpfh7gtult/src/virtualenv/util/path/_pathlib/via_os_path.py
/tmp/tmpfh7gtult/src/virtualenv/util/path/_pathlib/__init__.py
/tmp/tmpfh7gtult/src/virtualenv/util/path/_permission.py
/tmp/tmpfh7gtult/src/virtualenv/util/path/__init__.py
/tmp/tmpfh7gtult/src/virtualenv/util/subprocess
/tmp/tmpfh7gtult/src/virtualenv/util/subprocess/_win_subprocess.py
/tmp/tmpfh7gtult/src/virtualenv/util/subprocess/__init__.py
/tmp/tmpfh7gtult/src/virtualenv/util/zipapp.py
/tmp/tmpfh7gtult/src/virtualenv/util/__init__.py
/tmp/tmpfh7gtult/src/virtualenv/__init__.py
/tmp/tmpfh7gtult/src/virtualenv/seed
/tmp/tmpfh7gtult/src/virtualenv/seed/via_app_data
/tmp/tmpfh7gtult/src/virtualenv/seed/via_app_data/via_app_data.py
/tmp/tmpfh7gtult/src/virtualenv/seed/via_app_data/pip_install
/tmp/tmpfh7gtult/src/virtualenv/seed/via_app_data/pip_install/base.py
/tmp/tmpfh7gtult/src/virtualenv/seed/via_app_data/pip_install/copy.py
/tmp/tmpfh7gtult/src/virtualenv/seed/via_app_data/pip_install/__init__.py
/tmp/tmpfh7gtult/src/virtualenv/seed/via_app_data/pip_install/symlink.py
/tmp/tmpfh7gtult/src/virtualenv/seed/via_app_data/__init__.py
/tmp/tmpfh7gtult/src/virtualenv/seed/embed
/tmp/tmpfh7gtult/src/virtualenv/seed/embed/pip_invoke.py
/tmp/tmpfh7gtult/src/virtualenv/seed/embed/wheels
/tmp/tmpfh7gtult/src/virtualenv/seed/embed/wheels/setuptools-44.1.0-py2.py3-none-any.whl
/tmp/tmpfh7gtult/src/virtualenv/seed/embed/wheels/pip-19.1.1-py2.py3-none-any.whl
/tmp/tmpfh7gtult/src/virtualenv/seed/embed/wheels/wheel-0.34.2-py2.py3-none-any.whl
/tmp/tmpfh7gtult/src/virtualenv/seed/embed/wheels/wheel-0.33.6-py2.py3-none-any.whl
/tmp/tmpfh7gtult/src/virtualenv/seed/embed/wheels/acquire.py
/tmp/tmpfh7gtult/src/virtualenv/seed/embed/wheels/setuptools-43.0.0-py2.py3-none-any.whl
/tmp/tmpfh7gtult/src/virtualenv/seed/embed/wheels/__init__.py
/tmp/tmpfh7gtult/src/virtualenv/seed/embed/wheels/pip-20.0.2-py2.py3-none-any.whl
/tmp/tmpfh7gtult/src/virtualenv/seed/embed/wheels/setuptools-46.1.3-py3-none-any.whl
/tmp/tmpfh7gtult/src/virtualenv/seed/embed/__init__.py
/tmp/tmpfh7gtult/src/virtualenv/seed/embed/base_embed.py
/tmp/tmpfh7gtult/src/virtualenv/seed/__init__.py
/tmp/tmpfh7gtult/src/virtualenv/seed/seeder.py
/tmp/tmpfh7gtult/src/virtualenv.egg-info
/tmp/tmpfh7gtult/src/virtualenv.egg-info/PKG-INFO
/tmp/tmpfh7gtult/src/virtualenv.egg-info/zip-safe
/tmp/tmpfh7gtult/src/virtualenv.egg-info/requires.txt
/tmp/tmpfh7gtult/src/virtualenv.egg-info/SOURCES.txt
/tmp/tmpfh7gtult/src/virtualenv.egg-info/top_level.txt
/tmp/tmpfh7gtult/src/virtualenv.egg-info/entry_points.txt
/tmp/tmpfh7gtult/src/virtualenv.egg-info/dependency_links.txt
/tmp/tmpfh7gtult/.dockerignore
/tmp/tmpfh7gtult/README.md
/tmp/tmpfh7gtult/.coveragerc
/tmp/tmpfh7gtult/setup.cfg
/tmp/tmpfh7gtult/LICENSE
/tmp/tmpfh7gtult/tox.ini
```

**Comment by runfalk** [comment]
So that install script is broken. We are working on getting a fixed one on getlektor.com, but there are some things that need to be sorted first. You can use this as a workaround for now:

```
curl -sf https://raw.githubusercontent.com/lektor/lektor-website/master/assets/installer.py|python3
```

**Comment by sporksmith** [comment]
Thanks! Got it now. Btw it didn't work without `sudo`:

```
Building wheels for collected packages: watchdog, EXIFRead, inifile, pathtools
  Running setup.py bdist_wheel for watchdog ... error
  Complete output from command /home/jnewsome/.local/lib/lektor/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-tth99wrw/watchdog/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp91_odvdlpip-wheel- --python-tag cp36:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for watchdog
  Running setup.py clean for watchdog
  Running setup.py bdist_wheel for EXIFRead ... error
  Complete output from command /home/jnewsome/.local/lib/lektor/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-tth99wrw/EXIFRead/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpzyrkf556pip-wheel- --python-tag cp36:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------

```

**Comment by runfalk** [comment]
What error did you get?

**Comment by sporksmith** [comment]
> What error did you get?

It's in the partial output pasted [above](https://github.com/lektor/lektor/issues/763#issuecomment-620849246). `error: invalid command 'bdist_wheel'`

**Comment by runfalk** [comment]
I see, that may be a problem we need to look into. It should install both with or without sudo.

**Comment by yagebu** [comment]
The install shell script doesn't exist anymore (and the python script will soon be deprecated/removed as well: #915).
