### ISSUE TITLE
Issue to install on ubuntu 14.04

### ISSUE THREAD

**Issue by dariubs** [lektor/lektor#8]
``` sh
Welcome to Lektor

This script will install Lektor on your computer.

  bin: /usr/local/bin
  app: /usr/local/lib/lektor

Continue? [Yn] y
New python executable in /usr/local/lib/lektor/bin/python
Installing setuptools, pip, wheel...done.
Collecting Lektor
/usr/local/lib/lektor/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading Lektor-1.0-py2-none-any.whl (1.9MB)
    100% |████████████████████████████████| 1.9MB 99kB/s 
Collecting Babel (from Lektor)
  Downloading Babel-2.1.1-py2.py3-none-any.whl (3.6MB)
    100% |████████████████████████████████| 3.6MB 95kB/s 
Collecting setuptools (from Lektor)
  Downloading setuptools-19.1.1-py2.py3-none-any.whl (463kB)
    100% |████████████████████████████████| 466kB 160kB/s 
Collecting Flask (from Lektor)
  Downloading Flask-0.10.1.tar.gz (544kB)
    100% |████████████████████████████████| 544kB 108kB/s 
Collecting inifile (from Lektor)
  Downloading inifile-0.2-py2-none-any.whl
Collecting mistune (from Lektor)
  Downloading mistune-0.7.1-py2.py3-none-any.whl
Collecting click>=6.0 (from Lektor)
  Downloading click-6.2-py2.py3-none-any.whl (70kB)
    100% |████████████████████████████████| 73kB 338kB/s 
Collecting EXIFRead (from Lektor)
  Downloading ExifRead-2.1.2-py2-none-any.whl (47kB)
    100% |████████████████████████████████| 49kB 134kB/s 
Collecting watchdog (from Lektor)
  Downloading watchdog-0.8.3.tar.gz (83kB)
    100% |████████████████████████████████| 86kB 122kB/s 
Requirement already up-to-date: pip in /usr/local/lib/lektor/lib/python2.7/site-packages (from Lektor)
Collecting Jinja2>=2.4 (from Lektor)
  Downloading Jinja2-2.8-py2.py3-none-any.whl (263kB)
    100% |████████████████████████████████| 266kB 121kB/s 
Collecting pytz>=0a (from Babel->Lektor)
  Downloading pytz-2015.7-py2.py3-none-any.whl (476kB)
    100% |████████████████████████████████| 479kB 117kB/s 
Collecting Werkzeug>=0.7 (from Flask->Lektor)
  Downloading Werkzeug-0.11.3-py2.py3-none-any.whl (305kB)
    100% |████████████████████████████████| 307kB 915kB/s 
Collecting itsdangerous>=0.21 (from Flask->Lektor)
  Downloading itsdangerous-0.24.tar.gz (46kB)
    100% |████████████████████████████████| 49kB 138kB/s 
Collecting PyYAML>=3.10 (from watchdog->Lektor)
  Downloading PyYAML-3.11.tar.gz (248kB)
    100% |████████████████████████████████| 249kB 1.8MB/s 
Collecting argh>=0.24.1 (from watchdog->Lektor)
  Downloading argh-0.26.1.tar.gz
Collecting pathtools>=0.1.1 (from watchdog->Lektor)
  Downloading pathtools-0.1.2.tar.gz
Collecting MarkupSafe (from Jinja2>=2.4->Lektor)
  Downloading MarkupSafe-0.23.tar.gz
Building wheels for collected packages: Flask, watchdog, itsdangerous, PyYAML, argh, pathtools, MarkupSafe
  Running setup.py bdist_wheel for Flask
  Stored in directory: /root/.cache/pip/wheels/d2/db/61/cb9b80526b8f3ba89248ec0a29d6da1bb6013681c930fca987
  Running setup.py bdist_wheel for watchdog
  Stored in directory: /root/.cache/pip/wheels/93/93/cf/e7a7eee3227b2720bc95e96fe35562c08224814a3adfe8e447
  Running setup.py bdist_wheel for itsdangerous
  Stored in directory: /root/.cache/pip/wheels/97/c0/b8/b37c320ff57e15f993ba0ac98013eee778920b4a7b3ebae3cf
  Running setup.py bdist_wheel for PyYAML
  Complete output from command /usr/local/lib/lektor/bin/python -c "import setuptools;__file__='/tmp/pip-build-EEFbyE/PyYAML/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpS09bJzpip-wheel-:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/yaml
  copying lib/yaml/tokens.py -> build/lib.linux-x86_64-2.7/yaml
  copying lib/yaml/loader.py -> build/lib.linux-x86_64-2.7/yaml
  copying lib/yaml/scanner.py -> build/lib.linux-x86_64-2.7/yaml
  copying lib/yaml/reader.py -> build/lib.linux-x86_64-2.7/yaml
  copying lib/yaml/parser.py -> build/lib.linux-x86_64-2.7/yaml
  copying lib/yaml/error.py -> build/lib.linux-x86_64-2.7/yaml
  copying lib/yaml/events.py -> build/lib.linux-x86_64-2.7/yaml
  copying lib/yaml/dumper.py -> build/lib.linux-x86_64-2.7/yaml
  copying lib/yaml/serializer.py -> build/lib.linux-x86_64-2.7/yaml
  copying lib/yaml/resolver.py -> build/lib.linux-x86_64-2.7/yaml
  copying lib/yaml/cyaml.py -> build/lib.linux-x86_64-2.7/yaml
  copying lib/yaml/composer.py -> build/lib.linux-x86_64-2.7/yaml
  copying lib/yaml/nodes.py -> build/lib.linux-x86_64-2.7/yaml
  copying lib/yaml/representer.py -> build/lib.linux-x86_64-2.7/yaml
  copying lib/yaml/__init__.py -> build/lib.linux-x86_64-2.7/yaml
  copying lib/yaml/emitter.py -> build/lib.linux-x86_64-2.7/yaml
  copying lib/yaml/constructor.py -> build/lib.linux-x86_64-2.7/yaml
  running build_ext
  creating build/temp.linux-x86_64-2.7
  checking if libyaml is compilable
  x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/check_libyaml.c -o build/temp.linux-x86_64-2.7/check_libyaml.o
  checking if libyaml is linkable
  x86_64-linux-gnu-gcc -pthread build/temp.linux-x86_64-2.7/check_libyaml.o -lyaml -o build/temp.linux-x86_64-2.7/check_libyaml
  building '_yaml' extension
  creating build/temp.linux-x86_64-2.7/ext
  x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c ext/_yaml.c -o build/temp.linux-x86_64-2.7/ext/_yaml.o
  ext/_yaml.c:8:22: fatal error: pyconfig.h: No such file or directory
   #include "pyconfig.h"
                        ^
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

  ----------------------------------------
  Failed building wheel for PyYAML
  Running setup.py bdist_wheel for argh
  Stored in directory: /root/.cache/pip/wheels/e4/96/31/ed4151f32f78e2ebec318bc7081d65077c6c1512b561d1b263
  Running setup.py bdist_wheel for pathtools
  Stored in directory: /root/.cache/pip/wheels/97/d9/56/198cec194e02660d647417d4ad60f100fffc390fb46d243be5
  Running setup.py bdist_wheel for MarkupSafe
  Stored in directory: /root/.cache/pip/wheels/94/a7/79/f79a998b64c1281cb99fa9bbd33cfc9b8b5775f438218d17a7
Successfully built Flask watchdog itsdangerous argh pathtools MarkupSafe
Failed to build PyYAML
Installing collected packages: pytz, Babel, setuptools, Werkzeug, MarkupSafe, Jinja2, itsdangerous, Flask, inifile, mistune, click, EXIFRead, PyYAML, argh, pathtools, watchdog, Lektor
  Found existing installation: setuptools 18.2
    Uninstalling setuptools-18.2:
      Successfully uninstalled setuptools-18.2
  Running setup.py install for PyYAML
    Complete output from command /usr/local/lib/lektor/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-EEFbyE/PyYAML/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-6fL1dX-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/lib/lektor/include/site/python2.7/PyYAML:
    running install
    running build
    running build_py
    running build_ext
    building '_yaml' extension
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c ext/_yaml.c -o build/temp.linux-x86_64-2.7/ext/_yaml.o
    ext/_yaml.c:8:22: fatal error: pyconfig.h: No such file or directory
     #include "pyconfig.h"
                          ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/local/lib/lektor/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-EEFbyE/PyYAML/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-6fL1dX-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/lib/lektor/include/site/python2.7/PyYAML" failed with error code 1 in /tmp/pip-build-EEFbyE/PyYAML
/usr/local/lib/lektor/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

All done!
```

**Comment by Siecje** [comment]
``` shell
sudo apt-get install python-dev
```

**Comment by dariubs** [comment]
After Install `python-dev` the result is like this:

``` sh
sudo curl -sf https://www.getlektor.com/install.sh | sudo sh
Welcome to Lektor

This script will install Lektor on your computer.

  bin: /usr/local/bin
  app: /usr/local/lib/lektor

Continue? [Yn] Y
New python executable in /usr/local/lib/lektor/bin/python
Installing setuptools, pip, wheel...done.
The directory '/home/classa/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/classa/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting Lektor
/usr/local/lib/lektor/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading Lektor-1.0-py2-none-any.whl (1.9MB)
    100% |████████████████████████████████| 1.9MB 46kB/s 
Requirement already up-to-date: Babel in /usr/local/lib/lektor/lib/python2.7/site-packages (from Lektor)
Collecting setuptools (from Lektor)
  Downloading setuptools-19.1.1-py2.py3-none-any.whl (463kB)
    100% |████████████████████████████████| 466kB 337kB/s 
Requirement already up-to-date: Flask in /usr/local/lib/lektor/lib/python2.7/site-packages (from Lektor)
Requirement already up-to-date: inifile in /usr/local/lib/lektor/lib/python2.7/site-packages (from Lektor)
Requirement already up-to-date: mistune in /usr/local/lib/lektor/lib/python2.7/site-packages (from Lektor)
Requirement already up-to-date: click>=6.0 in /usr/local/lib/lektor/lib/python2.7/site-packages (from Lektor)
Requirement already up-to-date: EXIFRead in /usr/local/lib/lektor/lib/python2.7/site-packages (from Lektor)
Collecting watchdog (from Lektor)
  Downloading watchdog-0.8.3.tar.gz (83kB)
    100% |████████████████████████████████| 86kB 1.5MB/s 
Requirement already up-to-date: pip in /usr/local/lib/lektor/lib/python2.7/site-packages (from Lektor)
Requirement already up-to-date: Jinja2>=2.4 in /usr/local/lib/lektor/lib/python2.7/site-packages (from Lektor)
Requirement already up-to-date: pytz>=0a in /usr/local/lib/lektor/lib/python2.7/site-packages (from Babel->Lektor)
Requirement already up-to-date: Werkzeug>=0.7 in /usr/local/lib/lektor/lib/python2.7/site-packages (from Flask->Lektor)
Requirement already up-to-date: itsdangerous>=0.21 in /usr/local/lib/lektor/lib/python2.7/site-packages (from Flask->Lektor)
Collecting PyYAML>=3.10 (from watchdog->Lektor)
  Downloading PyYAML-3.11.tar.gz (248kB)
    100% |████████████████████████████████| 249kB 101kB/s 
Collecting argh>=0.24.1 (from watchdog->Lektor)
  Downloading argh-0.26.1.tar.gz
Collecting pathtools>=0.1.1 (from watchdog->Lektor)
  Downloading pathtools-0.1.2.tar.gz
Requirement already up-to-date: MarkupSafe in /usr/local/lib/lektor/lib/python2.7/site-packages (from Jinja2>=2.4->Lektor)
Installing collected packages: setuptools, PyYAML, argh, pathtools, watchdog, Lektor
  Found existing installation: setuptools 18.2
    Uninstalling setuptools-18.2:
      Successfully uninstalled setuptools-18.2
  Running setup.py install for PyYAML
  Running setup.py install for argh
  Running setup.py install for pathtools
  Running setup.py install for watchdog
Successfully installed Lektor-1.0 PyYAML-3.11 argh-0.26.1 pathtools-0.1.2 setuptools-19.1.1 watchdog-0.8.3
Traceback (most recent call last):
  File "<stdin>", line 100, in <module>
  File "<stdin>", line 95, in main
  File "<stdin>", line 59, in install
OSError: [Errno 17] File exists
```

I tried both on ubuntu server and ubnuntu desktop 14.04.

**Comment by mitsuhiko** [comment]
@dariubs just wipe `/usr/local/lib/lektor` and try again.

**Comment by mitsuhiko** [comment]
This is a documentation issue and the installer should wipe automatically.

**Comment by niijv** [comment]
Reflected in documentation now and the installer wipes upon confirmation. 
See https://github.com/lektor/lektor-website/commit/283fbcd8191c846812da49352f6c425f353be277
