### ISSUE TITLE
ModuleNotFoundError: No module named 'werkzeug.posixemulation'

### ISSUE THREAD

**Issue by kevinmoilar** [lektor/lektor#947]
Running Lektor installed via apt on debian bookworm form the testing repo (lektor/testing,testing,now 3.1.3-1) the command `lektor server` gives the following error:

_lektor server                        
Traceback (most recent call last):
  File "/usr/bin/lektor", line 11, in <module>
    load_entry_point('Lektor==3.1.3', 'console_scripts', 'lektor')()
  File "/home/kevin/.local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 474, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/kevin/.local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2846, in load_entry_point
    return ep.load()
  File "/home/kevin/.local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/home/kevin/.local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/lektor/cli.py", line 11, in <module>
    from .utils import secure_url
  File "/usr/lib/python3/dist-packages/lektor/utils.py", line 28, in <module>
    from werkzeug.posixemulation import rename
ModuleNotFoundError: No module named 'werkzeug.posixemulation'_

A **workaround** is to `pip3 install werkzeug==0.15.5`

**Comment by dairiki** [comment]
This appears to be a bug report having to do with the Debian-packaged version of lektor. You may want to file a report with [Debian's bug tracking system](https://bugs.debian.org/cgi-bin/pkgreport.cgi?pkg=lektor;dist=unstable).

Also note that version 3.1.3 of lektor (released January 2019) is fairly old, so the materialization of dependency-staleness issues are not overly surprising.  (The latest release is 3.2.2.)

I'm closing this issue here, since we no longer support 3.1.3.
